/**
 * Hightouchクイズ 問題バンク（100問）
 * difficulty: 1=初級, 2=中級, 3=上級
 * category: basics / reverse_etl_usecase / customer_studio / workspace_mgmt / integrations / competitors / security
 */
export const questions = [
  // ===== BASICS（25問） =====
  {
    id: 'b01',
    text: 'Hightouchとはどんなツールですか？',
    type: 'multiple_choice',
    options: [
      'メールマーケティング専用ツール',
      'データウェアハウス（DWH）のデータをマーケティングツールに自動送信するツール',
      'データウェアハウスを構築・設計するツール',
      '広告クリエイティブをAIで自動生成するツール',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは「Reverse ETL / Composable CDP」プラットフォームです。Snowflake・BigQuery・DatabricksなどのDWHに蓄積されたデータを、Salesforce・MoEngage・Google Adsなどのマーケティングツールへ自動的に同期します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b02',
    text: '「Reverse ETL（リバースETL）」とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'データをクラウドに送ること',
      'データウェアハウスのデータを各マーケティングツールに同期すること',
      'データを削除・クリーニングすること',
      'データを変換して分析レポートを作ること',
    ],
    correctIndex: 1,
    explanation: 'ETLは「Extract（抽出）→ Transform（変換）→ Load（格納）」の略で、データをDWHに集める流れです。Reverse ETLはその逆で、DWHに蓄積されたデータを各種ツールに「戻す・配信する」流れを指します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b03',
    text: 'Hightouchが「Reverse ETL」と呼ばれる理由はどれですか？',
    type: 'multiple_choice',
    options: [
      '通常のETL（データをDWHに集める流れ）とは逆方向にデータを流すから',
      'データを逆順に並べ替えるから',
      '古いETLツールへの対抗として作られたから',
      'データを逆向きに変換・加工するから',
    ],
    correctIndex: 0,
    explanation: '一般的なETLは「各システム → DWH」の方向でデータを集約します。Hightouchはその逆で「DWH → 各マーケティングツール」の方向にデータを流すため、Reverse ETLと呼ばれます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b04',
    text: 'Hightouchを使うために必要な前提条件はどれですか？',
    type: 'multiple_choice',
    options: [
      'Salesforceを契約していること',
      'データウェアハウス（DWH）を持っていること',
      '社内にエンジニアが複数名いること',
      '広告キャンペーンをすでに運用していること',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWHのデータを各ツールに同期するツールです。そのため、まずSnowflake・BigQuery・Databricksなどのデータウェアハウスが必要です。DWHなしには機能しません。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b05',
    text: 'HightouchのデータソースとなるDWH（データウェアハウス）として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'Salesforce・HubSpot・Marketo',
      'Snowflake・BigQuery・Databricks',
      'Google Analytics・Adobe Analytics',
      'Slack・Zoom・Teams',
    ],
    correctIndex: 1,
    explanation: 'HightouchのSourceとして接続できるDWHには、Snowflake・BigQuery・Databricks・Redshift・Azure Synapseなどが含まれます。Salesforceなどのツールは「送り先（Destination）」側です。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b06',
    text: '「Composable CDP」とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'CDPメーカーが新しく作ったブランド名',
      '様々なツールを組み合わせて自由にCDP（顧客データ基盤）を構築できる考え方',
      'データを圧縮・最適化して保存する技術',
      'APIを通じて外部サービスと接続するだけの機能',
    ],
    correctIndex: 1,
    explanation: 'Composable CDPは「DWH + BI + Reverse ETLなどを組み合わせて、パッケージ型CDPに頼らずCDP機能を実現する」考え方です。Hightouchはそのアプローチの中核ツールとして位置づけられています。',
    source: 'QA表 No.117',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b07',
    text: '従来の「パッケージ型CDP」（Treasure DataなどのSaaS型）とHightouchの最大の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchの方が常に安い',
      '従来CDPは独自基盤にデータをコピーするが、HightouchはDWHのデータをそのまま活用する',
      'Hightouchはメール配信機能を内蔵している',
      '従来CDPは日本語に対応していない',
    ],
    correctIndex: 1,
    explanation: 'Treasure DataなどのパッケージCDPは自社クラウドにデータを保管するため「データの二重管理」が発生します。HightouchはDWHのデータを直接参照するため、データのコピーが不要でリアルタイム性が高まります。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b08',
    text: 'Hightouchの「Sync（シンク）」とは何ですか？',
    type: 'multiple_choice',
    options: [
      '社内カレンダーの同期機能',
      '「どのデータを」「どのツールに」「どのように送るか」を定義したデータ連携設定',
      'チームメンバーとのファイル共有機能',
      'DWHへのデータ取り込み処理',
    ],
    correctIndex: 1,
    explanation: 'SyncはHightouchの基本単位です。「このAudienceのデータを、MoEngageのこのプロパティに、毎日0時に同期する」のような設定がSyncです。QA表では「どのデータを送るか＋どこに送るかの設定」と説明されています。',
    source: 'QA表 No.2',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b09',
    text: 'Hightouchの料金は何に基づいて決まりますか？',
    type: 'multiple_choice',
    options: [
      '連携しているユーザー数（MTU・月間トラッキングユーザー数）',
      '月間のデータ量（GBやTB）',
      '実行しているSync（データ連携設定）の本数',
      '接続したDestinationツールの数',
    ],
    correctIndex: 2,
    explanation: 'Hightouchは「Active Sync数（過去28日間で1回以上実行されたSync数）」に基づいて課金されます。MTU（ユーザー数）・データ量・シート数は課金対象外のため、ユーザーが増えても費用は上がりません。',
    source: 'docs/hightouch-product.md / QA表 No.2',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b10',
    text: 'Hightouchを使う主なメリットとして正しくないものはどれですか？',
    type: 'multiple_choice',
    options: [
      'エンジニアに頼まずマーケターが自分でセグメントを作れる',
      'DWHのデータをそのままマーケティングに活用できる',
      'データウェアハウスを新たに構築してくれる',
      '手動CSVアップロードの作業を自動化できる',
    ],
    correctIndex: 2,
    explanation: 'HightouchはDWHのデータを活用するツールですが、DWH自体を構築する機能はありません。Snowflake・BigQueryなどのDWHが先に必要です。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b11',
    text: 'HightouchはDWH側のデータを変更・削除しますか？',
    type: 'true_false',
    options: ['○ 変更・削除することがある', '× 変更・削除しない（読み取りのみ）'],
    correctIndex: 1,
    explanation: 'HightouchはDWHのデータを「読み取る」だけです。DWH内のデータを書き換えたり削除したりすることはありません。これはセキュリティと信頼性の観点で重要な設計思想です。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b12',
    text: 'Hightouchの日本での販売はどのように行われていますか？',
    type: 'multiple_choice',
    options: [
      'Hightouch社が日本法人を設立して直接販売している',
      'DearOneが日本国内独占販売代理店として販売している',
      '複数のパートナー企業が競合して販売している',
      'Amazon・Salesforceのマーケットプレイスで誰でも購入できる',
    ],
    correctIndex: 1,
    explanation: 'DearOneはHightouchの日本国内独占販売代理店です。日本でHightouchを使うには原則DearOneを通じる必要があります。直接Hightouch社と契約することも技術的には可能ですが、サポートは英語対応になります。',
    source: 'QA表 No.118 / docs/dearone-context.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b13',
    text: 'Hightouchの創業メンバーはもともとどのツールの出身ですか？',
    type: 'multiple_choice',
    options: [
      'Salesforce',
      'Segment（Twilio傘下のCDP）',
      'HubSpot',
      'Google Analytics',
    ],
    correctIndex: 1,
    explanation: 'HightouchはSegmentのエンジニアたちが「CDPをDWH中心のアーキテクチャで再設計する」という思想で創業しました。SegmentはCDPの先駆者ですが、HightouchはDWHを核とした次世代のComposable CDPとして設計されています。',
    source: 'QA表 No.116',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b14',
    text: 'Hightouchを使うことでエンジニアとマーケターの関係はどう変わりますか？',
    type: 'multiple_choice',
    options: [
      'エンジニアが不要になる',
      'マーケターが自分でセグメントを作れるため、エンジニアへの依頼が大幅に減る',
      'エンジニアの仕事が増える',
      '特に変わらない',
    ],
    correctIndex: 1,
    explanation: '従来は「新しいセグメントを作るたびにエンジニアにSQL開発を依頼する」というボトルネックが発生していました。Hightouchのノーコード機能（Customer Studio）により、マーケターが直接セグメントを作れるようになります。',
    source: 'docs/competitors.md / QA表 No.114',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b15',
    text: 'Hightouchが解決できる課題として最も適切なものはどれですか？',
    type: 'multiple_choice',
    options: [
      '新しいデータウェアハウスの選定・導入支援',
      'DWHにはデータが蓄積されているが、マーケティングツールで活用できていない状況',
      '社内コミュニケーションツールの効率化',
      '財務・会計システムの自動化',
    ],
    correctIndex: 1,
    explanation: '「DWHにはデータが蓄積されているが、マーケティングには活用できていない」という課題がHightouchの出発点です。QA表でも「CDPがない・既存システムを乗り換えたい・DWHから活用したい」という企業に向いていると説明されています。',
    source: 'QA表 No.114 / docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b16',
    text: 'Hightouchを使いこなすために、SQLやプログラミングの高度な知識は必ず必要ですか？',
    type: 'true_false',
    options: ['○ 必須。SQLなしでは使えない', '× 基本機能はノーコードで使える。SQLを書くとさらに柔軟に活用できる'],
    correctIndex: 1,
    explanation: 'Customer StudioはSQLなしで使えるノーコードUIです。ただし、DWHのモデル定義やカスタムセグメントにはSQLが役立ちます。マーケター向けの基本操作はSQLなしで完結します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b17',
    text: 'Hightouchのセグメントを作成しただけで（まだ同期を実行していない）、Sync数にカウントされますか？',
    type: 'true_false',
    options: ['○ セグメント作成時点でカウントされる', '× 実際にデータ同期（Sync実行）した時点からカウントされる'],
    correctIndex: 1,
    explanation: 'Hightouchの料金はActive Sync数（過去28日間で少なくとも1回実行されたSync数）に基づきます。セグメントを作るだけでは料金は発生しません。Syncを実行して初めてカウントされます。',
    source: 'QA表 No.87',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b18',
    text: 'HightouchはSOC 2 Type IIとISO 27001の認証を取得していますか？',
    type: 'true_false',
    options: ['○ 両方取得済み', '× どちらも取得していない'],
    correctIndex: 0,
    explanation: 'HightouchはSOC 2 Type IIとISO 27001の両方の認証を取得済みです。また、GDPR・CCPA・HIPAAにも対応しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b19',
    text: '「データウェアハウスをSingle Source of Truth（唯一の正となるデータ源）として使う」とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'DWHに保存されたデータを正として、そこから各ツールにデータを配信する',
      'DWHにあるすべてのデータを外部に公開する',
      'データを一つのツールだけに送る',
      'データウェアハウスを外部向けに開放する',
    ],
    correctIndex: 0,
    explanation: 'Single Source of Truthとは「DWHこそが最も正確・最新のデータ」という設計思想です。各ツールに散らばったデータをDWHに集約し、そこから正しいデータを各ツールに配信することで、データの一貫性が保たれます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b20',
    text: 'HightouchはDWHのデータを「保有・コピー」しますか？',
    type: 'true_false',
    options: ['○ Hightouchにデータをコピーして保管する', '× DWHのデータを読み取るだけで、Hightouch側にデータを永続保存しない'],
    correctIndex: 1,
    explanation: 'Hightouchのデータ非保存設計は重要なポイントです。データはDWHに置いたまま、必要な時だけ読み取って連携先ツールに送ります。Hightouch側にデータが溜まることはありません。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b21',
    text: '「Hightouchの管理レイヤー」があることのメリットとして正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'データを安く保管できる',
      'エラー確認・差分更新・スケジュール管理などデータ連携の運用を一元管理できる',
      'レポートが自動生成される',
      'ツールの契約管理ができる',
    ],
    correctIndex: 1,
    explanation: '「以前はCDPからSalesforceにデータが連携されていたが、失敗した原因が分からなかった」というような課題をHightouchは解決します。行単位のエラー確認・差分更新（全件再送不要）・スケジュール管理が一画面でできます。',
    source: 'QA表 No.128 / QA表 No.120',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b22',
    text: 'HightouchのBusinessプランでWorkspace（管理区画）はいくつ作れますか？',
    type: 'multiple_choice',
    options: [
      '最大3つまで',
      '最大10まで',
      '無制限に作成できる',
      '追加Workspaceには別途費用がかかる',
    ],
    correctIndex: 2,
    explanation: 'Businessプランではワークスペースを無制限に作成できます。グループ会社・部門・リージョン（日本/米国/欧州）などでWorkspaceを分けて管理することが可能です。',
    source: 'QA表 No.65',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b23',
    text: 'Hightouchを使うと「データの二重管理」が解消できるのはなぜですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchがデータを削除するから',
      'DWHのデータをそのまま各ツールに送るため、別のCDPにデータをコピーする必要がなくなるから',
      'Hightouchがデータを自動的に統合・圧縮するから',
      'クラウドが自動でデータを統合するから',
    ],
    correctIndex: 1,
    explanation: 'Treasure DataなどのパッケージCDPを使う場合、DWHにあるデータをCDPにも再投入する必要があり、データの二重管理が発生します。HightouchはDWHを直接参照するため、この問題がなくなります。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b24',
    text: 'Hightouchと直接契約するとどうなりますか？',
    type: 'multiple_choice',
    options: [
      '日本語サポートも含めて普通に使える',
      '技術的には可能だが、サポートは英語対応のみになる（DearOneのサポートなし）',
      '日本では直接契約が完全に不可能',
      '企業規模が大きくないと直接契約できない',
    ],
    correctIndex: 1,
    explanation: 'DearOneを通じず直接Hightouch社と契約することは技術的には可能ですが、QAサポート・契約関連の対応はすべて英語になります。DearOneを通じると日本語サポートが受けられます。',
    source: 'QA表 No.94',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b25',
    text: 'Hightouchの機能（Reverse ETL・Customer Studio・AI Decisioningなど）はすべてセットで購入しますか？',
    type: 'multiple_choice',
    options: [
      'すべてセットで購入する必要がある',
      '機能単位で選択して契約でき、追加で契約することもできる',
      '年間契約のみで月次変更は不可',
      'すべて無料で使える',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは機能単位（Reverse ETL / Customer Studio / AI Decisioning など）で選択して契約できます。まず必要な機能から始めて、追加の機能を後から契約することも可能です。',
    source: 'QA表 No.115',
    difficulty: 2,
    category: 'basics',
  },

  // ===== REVERSE ETL USECASE（20問） =====
  {
    id: 'u01',
    text: 'Hightouchが最も活用されるユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      '社内ドキュメントの全文検索',
      'DWHに蓄積した顧客データをMAツールや広告プラットフォームに自動配信',
      '社員の勤怠管理の自動化',
      '在庫管理の最適化',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの最も典型的なユースケースは「DWHに蓄積した顧客データをMoEngage・Salesforce・Google Adsなどに自動同期し、マーケティングに活用する」ことです。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u02',
    text: '「手動CSVアップロード」をHightouchで自動化するメリットとして正しくないものは？',
    type: 'multiple_choice',
    options: [
      '毎週・毎月の定型作業が自動化できる',
      '常に最新のデータで配信できる',
      '人的ミスがなくなる',
      '配信するメッセージの内容まで自動的に最適化される',
    ],
    correctIndex: 3,
    explanation: 'Hightouchはデータの同期・配信を自動化しますが、メール文面やクリエイティブの内容を自動最適化するものではありません（AI Decisioningは別の機能）。作業の自動化・データ鮮度の向上・ヒューマンエラーの防止が主なメリットです。',
    source: 'docs/competitors.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u03',
    text: 'Amplitude（分析ツール）単体では難しいことをHightouchを組み合わせると実現できます。それは何ですか？',
    type: 'multiple_choice',
    options: [
      'ユーザーの行動データを分析できる',
      'AmplitudeのセグメントをGoogle AdsやMoEngageなど他ツールに連携して活用できる',
      'リアルタイムのイベント計測ができる',
      'ダッシュボードや可視化レポートを作成できる',
    ],
    correctIndex: 1,
    explanation: 'AmplitudeはBIツールとして優秀ですが、そのセグメントを広告プラットフォームやMAツールに連携する機能は限られています。HightouchはDWHにあるAmplitudeのデータを各ツールに自由に連携できます。',
    source: 'QA表 No.113',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u04',
    text: 'Hightouchを使うと「差分更新」が可能になります。これはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      '毎回すべてのデータを送り直す（フルリフレッシュ）',
      '前回の同期から変更があったデータだけを送ることで、効率的に連携できる',
      'データを差し引き計算して送る',
      '古いデータを削除して新しいデータと置き換える',
    ],
    correctIndex: 1,
    explanation: '差分更新（Change Data Capture / CDC）により、前回のSync実行以降に変更・追加されたレコードのみを送ります。これにより処理時間の短縮とDWHへの負荷軽減が実現できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u05',
    text: '大量データ（例：1,000万件のユーザー）を連携する場合、Hightouchのパフォーマンスはどう影響を受けますか？',
    type: 'multiple_choice',
    options: [
      'Hightouchのサーバーが重くなりサービスが停止するリスクがある',
      '処理速度はデータソースであるDWH（Snowflake・BigQueryなど）のパフォーマンスに依存する',
      'データ量が多いほどHightouchの料金が急激に上昇する',
      '1億件以上のデータは処理できない',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの処理速度はDWH側のクエリ実行性能に依存します。日本の通信事業者で1日数千万行のデータをSnowflakeから各分析ツールに連携している実績もあります。',
    source: 'QA表 No.50 / QA表 No.26',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u06',
    text: '次のシナリオでHightouchが役立つのはどれですか？',
    type: 'multiple_choice',
    options: [
      '新しいデータウェアハウスを安く構築したい',
      '顧客の購買履歴データがSnowflakeにあり、それをMoEngageに同期してリターゲティングをしたい',
      '社内のSlackメッセージを翻訳したい',
      '従業員の人事評価システムを作りたい',
    ],
    correctIndex: 1,
    explanation: '「DWHにある購買データ → MoEngage/Braze/MA → リターゲティング」はHightouchの典型的なユースケースです。DWHのデータを起点に各マーケティングアクションを実行できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u07',
    text: 'DWHにある顧客データをSalesforceに同期するとき、Hightouchはどんな役割をしますか？',
    type: 'multiple_choice',
    options: [
      'SalesforceのCRM機能をDWHで置き換える',
      'DWHのデータを定期的に読み取り、Salesforceに自動反映するパイプラインを管理する',
      'SalesforceからDWHにデータを取り込む',
      'データを変換してCSVファイルを生成する',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWH→Salesforceの「パイプライン管理者」の役割を担います。設定したスケジュール・条件に従ってデータを自動同期し、Salesforceのリードや取引先情報を常に最新状態に保てます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u08',
    text: 'Hightouchを使うと、同期のエラー（例：特定のレコードが連携先ツールに入らなかった）はどのように確認できますか？',
    type: 'multiple_choice',
    options: [
      'エラーは手動でログファイルを調べる必要がある',
      '行（レコード）単位でリアルタイムにエラーを確認できる',
      'エラーが発生しても通知されない',
      'エラーは月1回のレポートで確認する',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの管理画面では、Sync実行ログを行単位で確認できます。「どのレコードが成功し、どのレコードが失敗したか・その理由」をリアルタイムに把握できます。',
    source: 'QA表 No.120',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u09',
    text: 'DWHのデータが整理されていない場合（例：複数テーブルに情報が分散している）、Hightouchは使えますか？',
    type: 'multiple_choice',
    options: [
      '使えない。DWHのデータが完全に整理されてから接続する必要がある',
      '使える。SQLを書いて複数テーブルを結合したデータをHightouchのモデルに設定できる',
      'Hightouchがデータを自動整理してくれる',
      '1テーブルのデータしか扱えない',
    ],
    correctIndex: 1,
    explanation: 'HightouchではSQL（クエリ）でデータを定義するため、複数テーブルをJOINしたデータや集計データも扱えます。「最終的に1つのキー（ユーザーID）で紐づければ」あとはSQLで対応できます。',
    source: 'QA表 No.127',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u10',
    text: 'ECサイト企業がHightouchを使う典型的なユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      '商品の自動発注管理',
      'DWHに蓄積した購買データからカート放棄ユーザーを抽出し、MAツールでリマーケティング',
      '倉庫の在庫管理最適化',
      '従業員の給与計算の自動化',
    ],
    correctIndex: 1,
    explanation: 'ECでの典型例は「カート放棄ユーザー・休眠顧客・高LTV顧客などをDWHのデータから抽出 → MoEngageやBrazeでプッシュ通知・メール配信」です。PetSmartでは6,500万人のロイヤリティ会員データを活用し増分売上15-25%増を実現しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u11',
    text: 'Hightouchで連携先ツール（Destination）として正式なコネクタがない場合でも連携できますか？',
    type: 'multiple_choice',
    options: [
      'できない。公式コネクタがないと使えない',
      'できる。REST APIを公開しているツールであればHTTP Requestデスティネーションで連携できる',
      'できるが、追加費用がかかる',
      'できるが、Hightouch社に個別開発を依頼する必要がある',
    ],
    correctIndex: 1,
    explanation: 'HightouchにはHTTP Requestというカスタムデスティネーション機能があります。KARTEなどの非公式コネクタでも、REST APIが公開されていれば連携が可能です。DearOneではSnowflake→KARTEの連携を検証済みです。',
    source: 'QA表 No.48 / QA表 No.96',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u12',
    text: 'HightouchはDWHにデータを書き戻す（DWHをDestinationとして使う）ことはできますか？',
    type: 'true_false',
    options: ['○ できる（SnowflakeやBigQueryをDestinationに設定できる）', '× できない（DWHはSourceのみ）'],
    correctIndex: 0,
    explanation: 'SnowflakeやBigQueryはSourceとしてだけでなく、Destinationとしても使えます。例えば「処理済みデータをDWHに書き戻す」ユースケースにも対応できます。',
    source: 'QA表 No.49',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u13',
    text: 'MAツール（例：MoEngage）の契約で「月間配信数の上限」がある場合、Hightouchではどう対処できますか？',
    type: 'multiple_choice',
    options: [
      '対処できない。Hightouchはすべてのデータを全件送信する',
      'Limit（件数制限）機能を使い、条件に合う上位N件のみを配信対象にできる',
      'MAツール側で制限する必要がある',
      'Syncを手動で停止する必要がある',
    ],
    correctIndex: 1,
    explanation: 'Hightouchには「Audience内の件数を上限Nまでに絞る」Limit機能や「TOP/BOTTOM Xパーセンタイル」機能があります。MAの配信上限に合わせてデータを絞り込んで送ることができます。',
    source: 'Hightouch公式ドキュメント（Limit機能）',
    difficulty: 3,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u14',
    text: '同じ顧客が広告・メール・LINEで重複して同じ配信を受けないようにするためにHightouchで使える機能はどれですか？',
    type: 'multiple_choice',
    options: [
      'Split（分割）機能',
      'Priority List（優先リスト）機能',
      'Match Booster機能',
      'Traits機能',
    ],
    correctIndex: 1,
    explanation: 'Priority List機能により「複数のAudienceに重複するユーザーがいる場合、どのAudience（＝施策）を優先するか」を設定できます。例えば「購買段階ごとのAudience A・B・Cで重複ユーザーは最も優先度の高いものだけに入れる」等の制御ができます。',
    source: 'QA表 No.57（類似ユースケース）',
    difficulty: 3,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u15',
    text: '「内製構築（社内エンジニアがスクリプトでデータ連携）」に対してHightouchが優れている点はどれですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchの方が必ず安い',
      '保守コストが低く、マーケターがセルフサービスで変更できる。新連携先の追加も開発不要',
      'Hightouchは完全ノーコードで何でもできる',
      '内製よりHightouchの方が常に処理が速い',
    ],
    correctIndex: 1,
    explanation: '内製構築の課題は「スクリプトの保守・エラー対応にエンジニアが張り付く・新連携先追加のたびに開発が必要・マーケター依頼のボトルネック」です。Hightouchはこれらをすべて解消できます。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u16',
    text: 'Hightouchを使った「広告パフォーマンス改善」の典型的なユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      '広告クリエイティブをAIが自動生成する',
      'DWHにある高LTV顧客データをGoogle AdsやMeta Adsに同期してターゲティング精度を高める',
      '広告予算を自動最適化する',
      '競合他社の広告を自動分析する',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWHの顧客データ（購買履歴・LTV・行動履歴等）をGoogle AdsやMeta Adsのカスタムオーディエンスに同期できます。Lucid Chartではこの手法でRASS +52%・工数95%削減を達成しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u17',
    text: 'HightouchでSync（データ連携）のスケジュールはどのように設定できますか？',
    type: 'multiple_choice',
    options: [
      '毎日決まった時間のみ設定できる',
      'リアルタイム・毎時・毎日・毎週など柔軟に設定でき、cron式での詳細設定も可能',
      '週1回のみ設定できる',
      'スケジュールは設定できず、手動実行のみ',
    ],
    correctIndex: 1,
    explanation: 'Hightouchのスケジュールは非常に柔軟で、リアルタイム・15分ごと・毎日特定の時間・特定の曜日など、cron式で細かく設定できます（例：「毎月第3月曜日」なども設定可能）。',
    source: 'QA表 No.85',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u18',
    text: 'HightouchでABテストを実施するためにどんな機能を使いますか？',
    type: 'multiple_choice',
    options: [
      'Filter機能でAとBのグループを別々に作る',
      'Split機能でAudienceを複数グループに分割し、それぞれ別のDestinationに送る',
      'Priority List機能でA/B優先順位を決める',
      'ABテストはHightouchの機能ではない',
    ],
    correctIndex: 1,
    explanation: 'Customer StudioのSplit機能を使うと、Audience内のユーザーを任意の比率で複数グループに分割できます。各グループを別々のSyncで異なるツール・設定に送ることでABテストを実施できます。',
    source: 'QA表 No.51（日本語）/ QA表 No.45（英語）',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u19',
    text: 'HightouchでPOC（概念実証）を実施する場合、通常どれくらいの期間が目安ですか？',
    type: 'multiple_choice',
    options: [
      '最低でも6ヶ月は必要',
      '1〜2週間程度で基本的な検証が可能。1ヶ月程度が一般的',
      '3ヶ月以上必要',
      '検証は本番導入後にしかできない',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは導入が早く、1〜2週間程度での基本的な検証が可能です。通常1ヶ月が目安で、無料アカウントで事前にトライしてからPOCに進む企業も多いです。',
    source: 'QA表 No.100',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u20',
    text: '「AIによるセグメントの自動生成・クラスタリング」はHightouchで可能ですか？',
    type: 'true_false',
    options: ['○ AIがセグメントを自動生成できる', '× セグメントの自動生成はできない。AI DecisioningはユーザーごとのAI最適化機能'],
    correctIndex: 1,
    explanation: 'Hightouchの「AI Decisioning」は「個々のユーザーに対して最適な次の行動を自動的に決定する」機能であり、「セグメントを自動生成する」機能ではありません。クラスタリングや類似オーディエンスの自動生成は提供していません。',
    source: 'QA表 No.126',
    difficulty: 3,
    category: 'reverse_etl_usecase',
  },

  // ===== CUSTOMER STUDIO（20問） =====
  {
    id: 'cs01',
    text: '「Customer Studio」とはHightouchのどんな機能ですか？',
    type: 'multiple_choice',
    options: [
      '顧客に請求書を発行する機能',
      'ノーコードでオーディエンス（セグメント）を作成・管理できるUI機能',
      '顧客とライブチャットをする機能',
      '社内顧客管理データベース',
    ],
    correctIndex: 1,
    explanation: 'Customer StudioはHightouchのノーコードUI機能です。SQLを書かなくても、条件を選択するだけで顧客セグメント（Audience）を作成できます。マーケターがセルフサービスでセグメントを管理できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs02',
    text: 'Customer Studioを使う主なユーザーはどんな人ですか？',
    type: 'multiple_choice',
    options: [
      'データエンジニアやデータサイエンティスト',
      'SQLを書けないマーケターやCRM担当者',
      '財務・経理担当者',
      'システム管理者のみ',
    ],
    correctIndex: 1,
    explanation: 'Customer StudioはノーコードUIのため、SQLの知識がなくても使えます。マーケター・CRM担当者・グロース担当者など、ビジネスサイドのメンバーが主なユーザーです。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs03',
    text: 'Customer StudioのAudience（オーディエンス）とは何ですか？',
    type: 'multiple_choice',
    options: [
      '配信するメール文章テンプレート',
      '特定の条件を満たすユーザーのグループ（セグメント）',
      '広告キャンペーンの設定',
      'ユーザーの行動ログファイル',
    ],
    correctIndex: 1,
    explanation: 'AudienceはCustomer Studioで作成するユーザーセグメントです。「過去30日以内に購入した」「累計購入額が1万円以上」などの条件でDWHのデータからユーザーグループを定義します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs04',
    text: 'Customer Studioでエンジニアへの依頼なしに、マーケター自身がセグメントを作成・変更できますか？',
    type: 'true_false',
    options: ['○ できる', '× 最終確認だけエンジニアが必要'],
    correctIndex: 0,
    explanation: 'Customer StudioのノーコードUIにより、マーケターが直接「条件の追加・削除・変更」を行えます。エンジニアへの依頼なしにセグメントを素早く作成・修正でき、マーケティング施策のスピードが上がります。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs05',
    text: 'Customer Studioで作成したAudienceのサイズ（対象ユーザー数）はどこで確認できますか？',
    type: 'multiple_choice',
    options: [
      'Salesforceのレポートで確認',
      'Customer Studio内で「Calculate Size」ボタンを押すと確認できる',
      'DWHを直接クエリして確認する必要がある',
      '同期を実行しないとサイズが分からない',
    ],
    correctIndex: 1,
    explanation: 'Audience作成画面の「Calculate Size」ボタンを押すと、設定した条件に合うユーザーが何人いるかを事前に確認できます。同期を実行する前にセグメントの規模を把握できます。',
    source: 'QA表 No.59 / QA表 No.70',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs06',
    text: 'Customer Studioの「Traits（トレイツ）」機能とは何ですか？',
    type: 'multiple_choice',
    options: [
      '連携先ツールのメッセージテンプレート機能',
      'ユーザーに計算済み属性値（例：過去90日の合計購入金額）をコードなしで追加できる機能',
      'セグメントに名前・ラベルをつける機能',
      'データを暗号化するセキュリティ機能',
    ],
    correctIndex: 1,
    explanation: 'Traitsは「COUNT・SUM・MAX・MIN・AVERAGE」などの集計をノーコードで設定し、ユーザーの属性値として使えるようにする機能です。例：「過去90日のCV回数」「累計購入金額」などを属性として付加できます。',
    source: 'docs/hightouch-product.md / QA表 No.54',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs07',
    text: 'Customer StudioでAudienceをSplit（分割）する主な目的は何ですか？',
    type: 'multiple_choice',
    options: [
      'データを小さくして処理を速くするため',
      'ABテストのためにユーザーを複数グループ（コントロール・テスト等）に分けるため',
      'DWHのデータを複数の場所に分散保存するため',
      'Audienceを削除するため',
    ],
    correctIndex: 1,
    explanation: 'Splitは主にABテストや実験的な施策のために使います。Audience内のユーザーをA/B/C等の複数グループにランダム分割し、各グループに異なる施策を実施して効果を比較できます。',
    source: 'QA表 No.51 / QA表 No.55（英語）',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs08',
    text: 'Customer Studioの「Priority List（優先リスト）」機能の主な用途は何ですか？',
    type: 'multiple_choice',
    options: [
      'セグメントを優先順位付きで表示するだけのUI機能',
      '複数Audienceに重複するユーザーが存在する場合、どのAudienceを優先するかを設定する機能',
      '配信時刻を優先順位で決める機能',
      '重要な顧客に特別割引を自動適用する機能',
    ],
    correctIndex: 1,
    explanation: 'Priority Listは「1人のユーザーが複数のAudienceに同時に入っている場合、どのAudienceを優先して適用するか」を決める機能です。例えば「購入前の顧客・購入後1ヶ月の顧客・休眠顧客」のAudienceで重複を制御できます。',
    source: 'QA表 No.79',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs09',
    text: 'Customer Studioの「Performance」機能では何を確認できますか？',
    type: 'multiple_choice',
    options: [
      'Hightouchサーバーの稼働状況・レスポンス速度',
      '時間軸に沿ったAudienceサイズの変化や、目標イベントの発生数',
      '配信したメールの開封率・クリック率',
      '広告のCPAやROAS（広告費用対効果）',
    ],
    correctIndex: 1,
    explanation: 'Performance機能はAmplitudeのセグメンテーションチャートに相当します。Audienceのユーザー数の増減・目標イベント（CV等）の発生状況を時系列で追跡できます。Lightning Sync Engineが必要です。',
    source: 'QA表 No.56 / QA表 No.7（英語）',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs10',
    text: 'Customer StudioでAudienceを作成するとき、その結果データは最終的にどこに送られますか？',
    type: 'multiple_choice',
    options: [
      'Hightouchのデータベースに永続保存される',
      '設定したSyncによってMoEngage・Google Adsなどの連携先ツールに送られる',
      'メールで担当者に自動送信される',
      'Excel/CSVファイルとしてダウンロードされる',
    ],
    correctIndex: 1,
    explanation: 'AudienceはCustomer Studioで定義するだけでは何も起きません。SyncでDestinationを設定し、実際に同期を実行することでMoEngage・Google Ads・Brazeなどの連携先にデータが送られます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs11',
    text: 'Customer Studioで「イベントデータ」（例：商品閲覧・カート追加イベント）は条件として使えますか？',
    type: 'true_false',
    options: ['○ 使える（SchemaでイベントテーブルをRelated Modelとして設定すれば使用可能）', '× 使えない（プロフィールデータのみ）'],
    correctIndex: 0,
    explanation: 'Customer StudioのSchemaでイベントテーブルをRelated Modelとして設定することで、イベントデータを条件に使えます。例えば「過去30日以内にカートに商品を追加したが購入していないユーザー」などのセグメントが作れます。',
    source: 'QA表 No.52',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs12',
    text: 'troccoとHightouchを比較したとき、Customer Studioのようなマーケター向けのセルフサービスUIはtroccoにありますか？',
    type: 'true_false',
    options: ['○ ある（troccoも同様のUIを持っている）', '× ない（troccoはエンジニア向けのETLツールで、Audience構築UIはない）'],
    correctIndex: 1,
    explanation: 'troccoはエンジニア向けのETL/リバースETLツールであり、マーケターがGUIで直接セグメントを作成するCustomer Studioのような機能はありません。これがHightouchの最大の差別化ポイントの一つです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs13',
    text: 'Customer Studioの「AI Decisioning」機能とはどんなものですか？',
    type: 'multiple_choice',
    options: [
      'AIがAudience条件を自動生成する機能',
      'AIが個々のユーザーに最適なメッセージ・チャネル・タイミングを自動で決定する機能',
      'AIが広告クリエイティブを自動生成する機能',
      'AIが最適なデータウェアハウスを選択する機能',
    ],
    correctIndex: 1,
    explanation: 'AI Decisioning（AID）は「1対1のパーソナライズ最適化」機能です。メールを送るか・プッシュ通知を送るか・いつ送るかをユーザーごとにAIが自動で最適化します。WHOOPでは6週間でCV +10%の成果を出しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs14',
    text: 'Customer StudioでAudienceの条件に使える集計（COUNT・SUMなど）を設定するのはどの機能ですか？',
    type: 'multiple_choice',
    options: [
      'Filter機能',
      'Schema機能',
      'Traits機能',
      'Split機能',
    ],
    correctIndex: 2,
    explanation: 'Traitsで「過去30日のCV数（COUNT）」「累計購入金額（SUM）」「最後の購入日（MAX）」などの集計値をユーザー属性として定義し、Audienceの条件に使えるようにします。',
    source: 'QA表 No.54 / QA表 No.80',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs15',
    text: 'Customer Studioの「Breakdown（内訳）」機能を使うとどんな分析ができますか？',
    type: 'multiple_choice',
    options: [
      'Audienceの会員属性別（性別・年齢帯・地域など）の構成比を確認できる',
      'データをアルファベット順に並べ替えられる',
      'DWHのテーブル構造を分析できる',
      '月別の売上推移を確認できる',
    ],
    correctIndex: 0,
    explanation: 'Breakdown機能は、作成したAudienceを特定の属性（性別・年齢帯・購買カテゴリなど）で分けた場合の構成比を確認できます。AmplitudeのUser Compositionチャートに相当します。',
    source: 'QA表 No.56',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs16',
    text: 'Customer Studioで「個人情報カラム」をUI上で非表示にするセキュリティ機能は何ですか？',
    type: 'multiple_choice',
    options: [
      'Encrypt（暗号化）機能',
      'Redact（リダクト）機能',
      'Private（プライベート）モード',
      'Shield（シールド）機能',
    ],
    correctIndex: 1,
    explanation: 'Redact機能を使うと、特定カラムの値をHightouch UI上でマスク（非表示）にできます。氏名・メールアドレスなどの個人情報を表示させずに、安全にAudienceの構築・確認ができます。',
    source: 'QA表 No.5',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs17',
    text: 'Customer Studioで「Audienceを保存するだけ（Syncを設定しない）」でもデータ連携はされますか？',
    type: 'true_false',
    options: ['○ される（Audienceを保存するとデータが送られる）', '× されない（SyncでDestinationを設定・実行して初めてデータが送られる）'],
    correctIndex: 1,
    explanation: 'Audienceの定義を保存するだけではデータは何も送られません。Syncを別途設定し、スケジュールまたは手動で実行することでDestinationにデータが送られます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs18',
    text: 'Customer Studioでセグメントを作成できる件数に上限はありますか？',
    type: 'true_false',
    options: ['○ 上限がある（最大100件まで）', '× 上限はない（制限なく作成できる）'],
    correctIndex: 1,
    explanation: 'Hightouchではソース・デスティネーション・シート数・セグメント数などの上限はありません。課金に影響するのはActive Sync数（実行したSync数）のみです。',
    source: 'QA表 No.13（英語版）',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs19',
    text: 'Customer Studioの「Schema（スキーマ）」設定とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'データを外部に公開するための設定',
      'Customer Studioで使うデータのテーブル構造（どのテーブルがどう関連するか）を定義する設定',
      'データの暗号化スキームを設定する',
      '配信スケジュールを設定する',
    ],
    correctIndex: 1,
    explanation: 'Schemaではデータモデルの構造（Parent Model・Related Model・Event Modelの関係性）を定義します。これにより、Customer Studioで「顧客情報テーブル」と「購買履歴テーブル」などを結びつけて条件として使えるようになります。',
    source: 'QA表 No.59',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs20',
    text: 'Customer Studioは「Customer Studio（セグメント構築）」と「Reverse ETL（Sync設定）」どちらか片方だけ使うことはできますか？',
    type: 'true_false',
    options: ['○ できる（それぞれ独立して契約・利用できる）', '× できない（セットで使わないといけない）'],
    correctIndex: 0,
    explanation: 'HightouchはReverse ETLとCustomer Studioを別々に契約して利用できます。例えば「Reverse ETLのみ」契約して、後から「Customer Studio」を追加することも可能です。',
    source: 'QA表 No.115',
    difficulty: 2,
    category: 'customer_studio',
  },

  // ===== WORKSPACE MANAGEMENT（10問） =====
  {
    id: 'ws01',
    text: 'Hightouchの「Workspace（ワークスペース）」とは何ですか？',
    type: 'multiple_choice',
    options: [
      'チームメンバーが作業するオフィス名',
      'ブランドや部門・リージョンごとにデータ連携設定を分けるHightouchの管理単位',
      'データを一時保管するストレージ',
      'ダッシュボードやレポートを共有する機能',
    ],
    correctIndex: 1,
    explanation: 'Workspaceはブランド・部門・リージョン（日本/US/EU）などを分けて管理するための区画です。Workspaceごとに独立したSource・Destination・Sync・ユーザー権限を持てます。',
    source: 'QA表 No.28',
    difficulty: 1,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws02',
    text: '複数のグループ会社でHightouchを利用する場合、Workspaceの扱いはどうなりますか？',
    type: 'multiple_choice',
    options: [
      'すべてのグループ会社を一つのWorkspaceで管理しなければならない',
      'グループ会社ごとに別々のWorkspaceを作成できるが、それぞれ別途ライセンス契約が必要',
      'BusinessプランならWorkspaceを無制限に作成でき、同一ライセンス内で複数グループ会社に対応できる',
      'グループ会社での共有は不可能',
    ],
    correctIndex: 2,
    explanation: 'Businessプランでは無制限のWorkspace作成が可能です。ただし、別グループ会社での利用は別途ライセンス契約が必要になります（費用が約2倍になる）。',
    source: 'QA表 No.65 / QA表 No.83',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws03',
    text: 'Hightouchでシングルサインオン（SSO）を使うには何が必要ですか？',
    type: 'multiple_choice',
    options: [
      '無料プランでも使える',
      'BusinessプランまたはEnterprise相当のプランへの加入が必要',
      'SSOは現在非対応',
      'エンジニアが自社でSAML認証サーバーを構築する必要がある',
    ],
    correctIndex: 1,
    explanation: 'SSOはHightouchのBusinessプランに含まれる機能です。SAML SSO（Okta・Azure ADなど）に対応しており、Businessプラン契約後に利用できます。',
    source: 'QA表 No.86',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws04',
    text: '1つのSyncを複数のWorkspaceで共有して使うことはできますか？',
    type: 'true_false',
    options: ['○ できる', '× できない（Workspaceごとに個別にSyncを作成する必要がある）'],
    correctIndex: 1,
    explanation: '現状、SyncはWorkspaceをまたいで共有できません。同じ設定のSyncが複数Workspaceで必要な場合は、それぞれのWorkspaceで個別に作成する必要があります。それぞれのSyncがActive Sync数にカウントされます。',
    source: 'QA表 No.69',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws05',
    text: 'Hightouchの利用ユーザー数（アカウント数）が増えた場合、追加費用はかかりますか？',
    type: 'true_false',
    options: ['○ かかる（アカウント数に応じて費用が増える）', '× かからない（アカウント数は課金対象外）'],
    correctIndex: 1,
    explanation: 'Hightouchの課金対象はActive Sync数のみです。アカウント数・シート数・ユーザー数は費用に影響しません。部門を増やしてもHightouchの費用は変わりません。',
    source: 'QA表 No.22',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws06',
    text: 'Hightouchの変更履歴管理（バージョン管理）はどの機能で実現できますか？',
    type: 'multiple_choice',
    options: [
      '管理画面の「変更履歴」タブ',
      'GitとのSync連携によるバージョン管理機能',
      '変更履歴の管理機能はない',
      'Audit Logのダウンロード機能',
    ],
    correctIndex: 1,
    explanation: 'HightouchはGitとの連携機能を持っており、Syncの設定をGitで管理できます。これによりSyncやModelの変更履歴管理・ロールバック・コードレビューが可能になります。',
    source: 'QA表 No.90',
    difficulty: 3,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws07',
    text: 'Hightouchにログインする際に使える認証方式として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'ID/パスワードのみ',
      'Google/Microsoft SSO、メールアドレス認証、SAML SSO（Okta等）に対応',
      'Googleアカウントのみ',
      '多要素認証（MFA）は非対応',
    ],
    correctIndex: 1,
    explanation: 'Hightouchのログイン方法はメールアドレス認証・Google/Microsoft SSO・SAML SSO（Okta・Azure ADなど）の複数方式に対応しています。パスワード要件はそれぞれの認証サービス側の設定に依存します。',
    source: 'QA表 No.29（英語）',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws08',
    text: '「カスタムロール（Custom Role）」を作成する主な目的は何ですか？',
    type: 'multiple_choice',
    options: [
      'アプリの見た目・テーマをカスタマイズするため',
      '部門・役割に応じてアクセスできる機能を制限し、セキュリティとガバナンスを強化するため',
      '連携先ツールへのアクセス権を外部管理するため',
      '課金プランを自動的に変更するため',
    ],
    correctIndex: 1,
    explanation: 'カスタムロールを使うと「この部門のユーザーはSourceの閲覧のみ可・Syncの変更は不可」のような細かい権限設定ができます。大企業でのセキュリティ・コンプライアンス要件に対応できます。',
    source: 'QA表 No.30',
    difficulty: 3,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws09',
    text: '検証用・テスト用Workspaceで実行したSyncはActive Sync数にカウントされますか？',
    type: 'true_false',
    options: ['○ カウントされる（検証用でも実際に同期実行するとカウントされる）', '× カウントされない'],
    correctIndex: 0,
    explanation: '検証・テスト目的であっても、Syncを実際に実行するとActive Sync数にカウントされます。本番とは別の検証用Workspaceでの実行も同様です。テスト専用の無課金ワークスペース機能は標準ではありません。',
    source: 'QA表 No.82',
    difficulty: 3,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws10',
    text: 'Workspaceを削除したい場合はどうしますか？',
    type: 'multiple_choice',
    options: [
      'Workspace設定画面から自分で削除できる',
      'Hightouch社に依頼して対応してもらう必要がある',
      'DearOneに削除を依頼する',
      '削除は不可能で、非アクティブ状態にするしかない',
    ],
    correctIndex: 1,
    explanation: 'WorkspaceはHightouch社に削除を依頼する必要があります（セルフサービスで削除できません）。誤って必要なWorkspaceを消してしまわないよう、この仕様になっています。',
    source: 'QA表 No.71',
    difficulty: 2,
    category: 'workspace_mgmt',
  },

  // ===== INTEGRATIONS（10問） =====
  {
    id: 'int01',
    text: 'HightouchとAmplitudeを組み合わせると何ができますか？',
    type: 'multiple_choice',
    options: [
      'AmplitudeのダッシュボードをHightouchで表示できる',
      'DWHにあるユーザーデータをGoogle AdsやMoEngageなど他ツールに連携できる',
      'Amplitudeの分析機能がHightouchに統合される',
      'AmplitudeのイベントをリアルタイムでSalesforceに送れる',
    ],
    correctIndex: 1,
    explanation: 'Amplitude単体では分析・セグメントの作成ができますが、そのセグメントを広告や他のMAに送る機能は限られています。HightouchはDWHにあるデータを活用し、Amplitudeのセグメントを各ツールに連携できます。',
    source: 'QA表 No.113',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int02',
    text: 'HightouchとMoEngageを連携させると何ができますか？',
    type: 'multiple_choice',
    options: [
      'MoEngageの管理画面をHightouchから操作できる',
      'DWHにある顧客セグメントをMoEngageに同期し、プッシュ通知・メール配信に活用できる',
      'MoEngageのデータをDWHに取り込める',
      'MoEngageの配信コストが削減される',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは「DWH → MoEngage（ユーザー属性・セグメントの同期）」のパイプラインを管理します。MoEngage側では最新の顧客データを使ったセグメント配信・パーソナライズ配信ができます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'integrations',
  },
  {
    id: 'int03',
    text: 'Google広告系でHightouchが標準コネクタで連携できるサービスはどれですか？',
    type: 'multiple_choice',
    options: [
      'Google Analytics・Google Search Console',
      'Google Ads・Google Ad Manager 360（有料版）',
      'Google Chrome・Google Drive・Gmail',
      'Google Cloud・Kubernetes Engine',
    ],
    correctIndex: 1,
    explanation: 'HightouchはGoogle Adsと連携してカスタムオーディエンスを同期できます。Google Ad Manager 360（GAM 360）はBusinessプランのみ対応です。無料版のGoogle Ad Managerは対応外です。',
    source: 'QA表 No.46 / QA表 No.47',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int04',
    text: 'HightouchのコネクタリストにないツールとHightouchを連携する方法は？',
    type: 'multiple_choice',
    options: [
      '連携は不可能',
      '「HTTP Request」デスティネーションを使い、REST APIで連携できる',
      'Hightouch社に有料カスタム開発を依頼する',
      'DearOneがすべてのツール向けのカスタムコネクタを無償で開発する',
    ],
    correctIndex: 1,
    explanation: 'HTTP RequestデスティネーションはJSON形式でREST APIにデータを送る汎用コネクタです。APIを公開しているツールであればほぼ連携できます。DearOneではKARTEとの連携を検証済みです。',
    source: 'QA表 No.48 / QA表 No.96',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int05',
    text: 'HightouchはTreasure Dataとの公式コネクタを持っていますか？',
    type: 'true_false',
    options: ['○ ある', '× ない（現時点でTreasure Dataとの公式コネクタはない）'],
    correctIndex: 1,
    explanation: 'Hightouchには現在Treasure Data向けの公式コネクタはあ��ません。HTTP Request経由での連携も、Treasure Data側のAPIが限定的なため容易ではありません。',
    source: 'QA表 No.88',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int06',
    text: 'HightouchでSnowflakeを使う場合、SourceとDestinationのどちらに使えますか？',
    type: 'multiple_choice',
    options: [
      'Sourceとしてのみ使える',
      'Destinationとしてのみ使える',
      'SourceとDestinationの両方として使える',
      'Snowflakeはコネクタに含まれていない',
    ],
    correctIndex: 2,
    explanation: 'Snowflakeは「DWHからデータを読む（Source）」としても、「処理済みデータをDWHに書き戻す（Destination）」としても使えます。BigQueryやDatabricksも同様です。',
    source: 'QA表 No.49',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int07',
    text: 'HightouchはAirflow（ワークフローツール）と連携できますか？',
    type: 'true_false',
    options: ['○ できる（HightouchのSyncをAirflowのワークフローに組み込めるOperatorが提供されている）', '× できない'],
    correctIndex: 0,
    explanation: 'HightouchはAirflow・Prefect・Airbyteなど外部ワークフローツールとの連携機能を提供しています。データパイプラインのオーケストレーションに組み込めます。',
    source: 'QA表 No.95 / QA表 No.97',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int08',
    text: 'VWO（Visual Website Optimizer）を使っているマーケターにとってHightouchはどう役立ちますか？',
    type: 'multiple_choice',
    options: [
      'VWOのABテストをHightouchが自動実行する',
      'DWHにある顧客属性データをVWOに送り、パーソナライズテストに活用できる',
      'VWOのヒートマップ分析をHightouchで実行できる',
      'VWOはHightouchと互換性がない',
    ],
    correctIndex: 1,
    explanation: 'HightouchのDestinationにはVWOも含まれています。DWHにある顧客セグメント（高LTV・新規・休眠等）をVWOに送ることで、セグメントベースのパーソナライズテストが実施できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int09',
    text: 'HightouchのSync実行速度（処理時間）に最も影響する要因は何ですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchのサーバースペック',
      'SourceであるDWH（Snowflake・BigQueryなど）のクエリ実行パフォーマンス',
      'インターネット回線速度',
      '連携先ツールのAPI制限',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWH側でデータを処理・抽出した後に連携先に送ります。そのため処理速度はDWHのクエリ性能に大きく依存します。DWH側のリソースを増やすことで高速化できます（Lightning Sync Engine利用時）。',
    source: 'QA表 No.50 / QA表 No.64',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int10',
    text: 'HightouchはdbtやFivetranなどのデータ変換・取り込みツールとどんな関係にありますか？',
    type: 'multiple_choice',
    options: [
      '競合関係にある',
      '補完関係にある（dbtでDWHのデータを整形→HightouchでMAや広告に送るという組み合わせが一般的）',
      'Hightouchがdbtを内蔵している',
      '連携できない',
    ],
    correctIndex: 1,
    explanation: 'dbtはDWH内のデータ変換（SQL変換・モデリング）、FivetranはデータをDWHに取り込む（ETL）ツールです。Hightouchはその後段で「DWH → マーケティングツール」の役割を担い、これらのツールと連携して使われます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'integrations',
  },

  // ===== COMPETITORS（10問） =====
  {
    id: 'cp01',
    text: 'Treasure DataとHightouchの最大の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'Treasure Dataは日本語非対応でHightouchは日本語対応',
      'Treasure DataはCDP独自基盤にデータを保有するが、HightouchはDWHのデータをそのまま活用する',
      'HightouchはTreasure Dataより機能が少ない',
      'Treasure Dataは広告連携に特化、HightouchはCRM連携に特化している',
    ],
    correctIndex: 1,
    explanation: 'Treasure Dataは自社クラウドにデータを保存するパッケージ型CDPです。Hightouchは既存DWHのデータをそのまま活用するため、データのコピー・二重管理が不要です。これが最大の設計思想の違いです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp02',
    text: 'Treasure Dataの料金モデルの特徴として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'Sync本数で課金される（Hightouchと同じ）',
      'データ投入量・保持プロファイル数に応じて課金され、ユーザー規模が大きいほど費用が増加する',
      '月額固定料金で使い放題',
      'APIコール数で課金される',
    ],
    correctIndex: 1,
    explanation: 'Treasure Dataはデータ量・プロファイル数課金のため、ユーザー数が増えるほど費用も増加します。一方HightouchはSync本数課金のため、ユーザーが増えても費用は変わりません。これは成長企業にとって大きな違いです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp03',
    text: 'troccoがHightouchより強みを持つ領域はどれですか？',
    type: 'multiple_choice',
    options: [
      'マーケター向けのセグメント構築ノーコードUI',
      'ETL（データをDWHに取り込む）機能',
      '広告プラットフォームへの連携数',
      'AI最適化・AI Decisioning機能',
    ],
    correctIndex: 1,
    explanation: 'troccoはETL（外部データをDWHに集める）の機能が強く、日本語対応でエンジニアに使いやすいツールです。一方HightouchはリバースETL（DWH→各ツール）とマーケター向けUI（Customer Studio）が強みです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp04',
    text: 'Hightouchとtroccoはどのような役割分担が可能ですか？',
    type: 'multiple_choice',
    options: [
      'troccoはHightouchの上位互換なので役割分担は不要',
      'ETL（データ取り込み）はtrocco、リバースETL（データ活用・配信）はHightouchで棲み分けできる',
      'troccoはHightouchと統合予定',
      'Hightouchはtroccoと公式パートナーシップを持つ',
    ],
    correctIndex: 1,
    explanation: 'troccoとHightouchは競合しながらも共存できます。「troccoで外部データをDWHに集め、HightouchでDWHのデータをMAや広告に配信する」という棲み分けは実際の導入パターンとして存在します。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp05',
    text: '「手動CSV運用」からHightouchへ移行した場合に最も期待できる効果はどれですか？',
    type: 'multiple_choice',
    options: [
      'データの量が自動的に増える',
      '毎週・毎月の手動作業がなくなり、常に最新データで自動配信できるようになる',
      '配信コストが0円になる',
      'ツールの機能サポートが充実する',
    ],
    correctIndex: 1,
    explanation: '手動CSV運用の課題は「定型作業の工数・データが古くなる・ヒューマンエラー」です。Hightouchに移行すると自動化・最新データ・エラーなしが実現できます。',
    source: 'docs/competitors.md',
    difficulty: 1,
    category: 'competitors',
  },
  {
    id: 'cp06',
    text: 'HightouchがSegmentと比較して最大の設計上の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'HightouchはSegmentより価格が安い',
      'HightouchはDWHを中核とするComposable CDPアーキテクチャを採用し、データをコピーしない',
      'HightouchはSegmentの機能を包含している',
      'SegmentはHightouchより連携先が少ない',
    ],
    correctIndex: 1,
    explanation: 'SegmentはデータをSegment側に集める仕組みですが、HightouchはDWHをそのままCDPとして使うComposable CDPアーキテクチャです。HightouchはSegmentの創業エンジニアがDWH中心に再設計したツールと言えます。',
    source: 'QA表 No.116',
    difficulty: 3,
    category: 'competitors',
  },
  {
    id: 'cp07',
    text: 'HightouchのSync本数課金がTreasure Data（プロファイル数課金）より成長企業に有利な理由は？',
    type: 'multiple_choice',
    options: [
      'Hightouchは常に安いから',
      'HightouchはSync本数課金のため、ユーザー数・データ量が増えても追加費用が発生しないから',
      'Hightouchは無制限プランを提供しているから',
      'Treasure Dataの品質が劣るから',
    ],
    correctIndex: 1,
    explanation: 'プロファイル数課金では「ユーザーが増える＝費用が増える」という構造になります。Hightouchはユーザー数・データ量が増えても課金はSyncの本数だけに依存するため、スケールしても費用が跳ね上がりません。',
    source: 'docs/competitors.md',
    difficulty: 3,
    category: 'competitors',
  },
  {
    id: 'cp08',
    text: '「パッケージ型CDP（Treasure DataやSegment）」を使うとデータ管理で発生しやすい課題はどれですか？',
    type: 'multiple_choice',
    options: [
      'データが暗号化されない',
      'DWHとCDP間でデータの二重管理・鮮度の問題が発生しやすい',
      'データが自動削除される',
      'ユーザー数に厳しい制限がある',
    ],
    correctIndex: 1,
    explanation: 'パッケージ型CDPではDWHのデータをCDPに再投入（コピー）する必要があり、「どちらが最新か分からない」「同期のタイムラグで鮮度が落ちる」「管理工数が2倍になる」などの課題が発生します。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp09',
    text: 'Hightouchに向いている企業・状況として最も正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'まだデータウェアハウスを持っていない企業',
      'CDPがない・既存システムを乗り換えたい・DWHを持っているがマーケティング活用できていない企業',
      '広告だけに活用したい企業',
      '大企業のみ（中小企業は不向き）',
    ],
    correctIndex: 1,
    explanation: 'QA表でも「CDPがない・既存システムから乗り換えたい・DWHと一緒に構築したい」企業に向いていると説明されています。DWHを既に持っているが活用できていない企業が最も典型的なターゲットです。',
    source: 'QA表 No.114',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp10',
    text: '「内製構築（スクリプトによるデータ連携）」の主なデメリットとして正しくないものはどれですか？',
    type: 'multiple_choice',
    options: [
      'エラー発生時のデバッグにエンジニアが張り付く必要がある',
      '新しい連携先が増えるたびに開発工数が必要',
      'データ処理速度が必ずHightouchより遅くなる',
      'マーケターがセグメントを変えたいときにエンジニアへの依頼が必要',
    ],
    correctIndex: 2,
    explanation: '内製構築のデメリットは「保守コスト・拡張コスト・マーケターのボトルネック・エラー管理の難しさ」です。処理速度は内製でも高速に実装できるため、速度が必ずHightouchより劣るわけではありません。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },

  // ===== SECURITY（5問） =====
  {
    id: 'sec01',
    text: 'Hightouchのデータセキュリティに関する最大の特徴はどれですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchは顧客データを自社サーバーに永続保存して管理する',
      'DWHからデータを読み取るだけで、Hightouch側にデータを永続保存しない「データ非保存設計」',
      'データはHightouch社が独自に暗号化して管理する',
      'セキュリティはDWH側の責任で、Hightouchは関与しない',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの重要な設計思想が「データ非保存」です。DWHからデータを読み取ってDestinationに送りますが、Hightouch側にデータを永続保存しません。これにより個人情報の漏洩リスクを最小化します。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'security',
  },
  {
    id: 'sec02',
    text: 'HightouchはGDPRやHIPAA（医療情報保護法）に対応していますか？',
    type: 'true_false',
    options: ['○ GDPR・CCPA・HIPAAのすべてに対応している', '× HIPAAには非対応'],
    correctIndex: 0,
    explanation: 'HightouchはGDPR（EU一般データ保護規則）・CCPA（カリフォルニア州消費者プライバシー法）・HIPAA（米国医療情報保護法）のすべてに対応しています。医療系企業への提案でも対応可能です。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'security',
  },
  {
    id: 'sec03',
    text: 'HightouchがデータをDWHから読み取る際の通信暗号化プロトコルは何ですか？',
    type: 'multiple_choice',
    options: [
      'HTTP（暗号化なし）',
      'TLS 1.2以上',
      'SSHトンネル',
      'FTP',
    ],
    correctIndex: 1,
    explanation: 'HightouchはTLS 1.2以上での通信暗号化を使用しています。また、AWS PrivateLinkやGCP Private Service Connectを使った閉域網接続にも対応しており、より高いセキュリティが求められる場合に選択できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 3,
    category: 'security',
  },
  {
    id: 'sec04',
    text: 'Hightouchが取得しているセキュリティ認証として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'ISO 9001・PCI DSS',
      'SOC 2 Type II・ISO 27001',
      'JIS Q 27001のみ',
      'HIPAA認定・FedRAMP',
    ],
    correctIndex: 1,
    explanation: 'HightouchはSOC 2 Type II（米国の情報セキュリティ監査）とISO 27001（国際標準のISMS認証）の両方を取得済みです。エンタープライズ・金融・医療系の企業への提案時に有効な証明です。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'security',
  },
  {
    id: 'sec05',
    text: 'Hightouchを使うと、Customer Studio上で個人情報（氏名・メールアドレス）のカラム値を非表示にすることはできますか？',
    type: 'true_false',
    options: ['○ できる（Redact機能でUI上の値を非表示にできる）', '× できない'],
    correctIndex: 0,
    explanation: 'Customer StudioのRedact（リダクト）機能を使うと、特定カラムの値をHightouch UI上でマスクできます。セキュリティ上の観点から、個人情報（PII）カラムをマーケターに見せずにセグメント構築できます。',
    source: 'QA表 No.5',
    difficulty: 3,
    category: 'security',
  },
];

export const CATEGORIES = {
  basics: '基礎知識',
  reverse_etl_usecase: 'リバースETL・ユースケース',
  customer_studio: 'Customer Studio',
  workspace_mgmt: 'Workspace管理',
  integrations: '連携・インテグレーション',
  competitors: '競合比較',
  security: 'セキュリティ',
};
