/**
 * Hightouchクイズ 問題バンク（100問）
 * difficulty: 1=初級, 2=中級, 3=上級
 * category: basics / reverse_etl_usecase / customer_studio / workspace_mgmt / integrations / competitors / security
 */
export const questions = [
  // ===== BASICS（25問） =====
  {
    id: 'b01',
    text: 'Hightouchとはどんなツールですか？',
    type: 'multiple_choice',
    options: [
      'メールマーケティング専用ツール',
      'データウェアハウス（DWH）のデータをマーケティングツールに自動送信するツール',
      'データウェアハウスを構築・設計するツール',
      '広告クリエイティブをAIで自動生成するツール',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは「Reverse ETL / Composable CDP」プラットフォームです。Snowflake・BigQuery・DatabricksなどのDWHに蓄積されたデータを、Salesforce・MoEngage・Google Adsなどのマーケティングツールへ自動的に同期します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b02',
    text: '「Reverse ETL（リバースETL）」とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'データをクラウドに送ること',
      'データウェアハウスのデータを各マーケティングツールに同期すること',
      'データを削除・クリーニングすること',
      'データを変換して分析レポートを作ること',
    ],
    correctIndex: 1,
    explanation: 'ETLは「Extract（抽出）→ Transform（変換）→ Load（格納）」の略で、データをDWHに集める流れです。Reverse ETLはその逆で、DWHに蓄積されたデータを各種ツールに「戻す・配信する」流れを指します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b03',
    text: 'Hightouchが「Reverse ETL」と呼ばれる理由はどれですか？',
    type: 'multiple_choice',
    options: [
      '通常のETL（データをDWHに集める流れ）とは逆方向にデータを流すから',
      'データを逆順に並べ替えるから',
      '古いETLツールへの対抗として作られたから',
      'データを逆向きに変換・加工するから',
    ],
    correctIndex: 0,
    explanation: '一般的なETLは「各システム → DWH」の方向でデータを集約します。Hightouchはその逆で「DWH → 各マーケティングツール」の方向にデータを流すため、Reverse ETLと呼ばれます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b04',
    text: 'Hightouchを使うために必要な前提条件はどれですか？',
    type: 'multiple_choice',
    options: [
      'Salesforceを契約していること',
      'データウェアハウス（DWH）を持っていること',
      '社内にエンジニアが複数名いること',
      '広告キャンペーンをすでに運用していること',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWHのデータを各ツールに同期するツールです。そのため、まずSnowflake・BigQuery・Databricksなどのデータウェアハウスが必要です。DWHなしには機能しません。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b05',
    text: 'HightouchのデータソースとなるDWH（データウェアハウス）として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'Salesforce・HubSpot・Marketo',
      'Snowflake・BigQuery・Databricks',
      'Google Analytics・Adobe Analytics',
      'Slack・Zoom・Teams',
    ],
    correctIndex: 1,
    explanation: 'HightouchのSourceとして接続できるDWHには、Snowflake・BigQuery・Databricks・Redshift・Azure Synapseなどが含まれます。Salesforceなどのツールは「送り先（Destination）」側です。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b06',
    text: '「Composable CDP」とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'CDPメーカーが新しく作ったブランド名',
      '様々なツールを組み合わせて自由にCDP（顧客データ基盤）を構築できる考え方',
      'データを圧縮・最適化して保存する技術',
      'APIを通じて外部サービスと接続するだけの機能',
    ],
    correctIndex: 1,
    explanation: 'Composable CDPは「DWH + BI + Reverse ETLなどを組み合わせて、パッケージ型CDPに頼らずCDP機能を実現する」考え方です。Hightouchはそのアプローチの中核ツールとして位置づけられています。',
    source: 'QA表 No.117',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b07',
    text: '従来の「パッケージ型CDP」（Treasure DataなどのSaaS型）とHightouchの最大の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchの方が常に安い',
      '従来CDPは独自基盤にデータをコピーするが、HightouchはDWHのデータをそのまま活用する',
      'Hightouchはメール配信機能を内蔵している',
      '従来CDPは日本語に対応していない',
    ],
    correctIndex: 1,
    explanation: 'Treasure DataなどのパッケージCDPは自社クラウドにデータを保管するため「データの二重管理」が発生します。HightouchはDWHのデータを直接参照するため、データのコピーが不要でリアルタイム性が高まります。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b08',
    text: 'Hightouchの「Sync（シンク）」とは何ですか？',
    type: 'multiple_choice',
    options: [
      '社内カレンダーの同期機能',
      '「どのデータを」「どのツールに」「どのように送るか」を定義したデータ連携設定',
      'チームメンバーとのファイル共有機能',
      'DWHへのデータ取り込み処理',
    ],
    correctIndex: 1,
    explanation: 'SyncはHightouchの基本単位です。「このAudienceのデータを、MoEngageのこのプロパティに、毎日0時に同期する」のような設定がSyncです。QA表では「どのデータを送るか＋どこに送るかの設定」と説明されています。',
    source: 'QA表 No.2',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b09',
    text: 'Hightouchの料金は何に基づいて決まりますか？',
    type: 'multiple_choice',
    options: [
      '連携しているユーザー数（MTU・月間トラッキングユーザー数）',
      '月間のデータ量（GBやTB）',
      '実行しているSync（データ連携設定）の本数',
      '接続したDestinationツールの数',
    ],
    correctIndex: 2,
    explanation: 'Hightouchは「Active Sync数（過去28日間で1回以上実行されたSync数）」に基づいて課金されます。MTU（ユーザー数）・データ量・シート数は課金対象外のため、ユーザーが増えても費用は上がりません。',
    source: 'docs/hightouch-product.md / QA表 No.2',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b10',
    text: 'Hightouchを使う主なメリットとして正しくないものはどれですか？',
    type: 'multiple_choice',
    options: [
      'エンジニアに頼まずマーケターが自分でセグメントを作れる',
      'DWHのデータをそのままマーケティングに活用できる',
      'データウェアハウスを新たに構築してくれる',
      '手動CSVアップロードの作業を自動化できる',
    ],
    correctIndex: 2,
    explanation: 'HightouchはDWHのデータを活用するツールですが、DWH自体を構築する機能はありません。Snowflake・BigQueryなどのDWHが先に必要です。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b11',
    text: 'HightouchはDWH側のデータを変更・削除しますか？',
    type: 'true_false',
    options: ['○ 変更・削除することがある', '× 変更・削除しない（読み取りのみ）'],
    correctIndex: 1,
    explanation: 'HightouchはDWHのデータを「読み取る」だけです。DWH内のデータを書き換えたり削除したりすることはありません。これはセキュリティと信頼性の観点で重要な設計思想です。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b12',
    text: 'Hightouchの日本での販売はどのように行われていますか？',
    type: 'multiple_choice',
    options: [
      'Hightouch社が日本法人を設立して直接販売している',
      'DearOneが日本国内独占販売代理店として販売している',
      '複数のパートナー企業が競合して販売している',
      'Amazon・Salesforceのマーケットプレイスで誰でも購入できる',
    ],
    correctIndex: 1,
    explanation: 'DearOneはHightouchの日本国内独占販売代理店です。日本でHightouchを使うには原則DearOneを通じる必要があります。直接Hightouch社と契約することも技術的には可能ですが、サポートは英語対応になります。',
    source: 'QA表 No.118 / docs/dearone-context.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b13',
    text: 'Hightouchの創業メンバーはもともとどのツールの出身ですか？',
    type: 'multiple_choice',
    options: [
      'Salesforce',
      'Segment（Twilio傘下のCDP）',
      'HubSpot',
      'Google Analytics',
    ],
    correctIndex: 1,
    explanation: 'HightouchはSegmentのエンジニアたちが「CDPをDWH中心のアーキテクチャで再設計する」という思想で創業しました。SegmentはCDPの先駆者ですが、HightouchはDWHを核とした次世代のComposable CDPとして設計されています。',
    source: 'QA表 No.116',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b14',
    text: 'Hightouchを使うことでエンジニアとマーケターの関係はどう変わりますか？',
    type: 'multiple_choice',
    options: [
      'エンジニアが不要になる',
      'マーケターが自分でセグメントを作れるため、エンジニアへの依頼が大幅に減る',
      'エンジニアの仕事が増える',
      '特に変わらない',
    ],
    correctIndex: 1,
    explanation: '従来は「新しいセグメントを作るたびにエンジニアにSQL開発を依頼する」というボトルネックが発生していました。Hightouchのノーコード機能（Customer Studio）により、マーケターが直接セグメントを作れるようになります。',
    source: 'docs/competitors.md / QA表 No.114',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b15',
    text: 'Hightouchが解決できる課題として最も適切なものはどれですか？',
    type: 'multiple_choice',
    options: [
      '新しいデータウェアハウスの選定・導入支援',
      'DWHにはデータが蓄積されているが、マーケティングツールで活用できていない状況',
      '社内コミュニケーションツールの効率化',
      '財務・会計システムの自動化',
    ],
    correctIndex: 1,
    explanation: '「DWHにはデータが蓄積されているが、マーケティングには活用できていない」という課題がHightouchの出発点です。QA表でも「CDPがない・既存システムを乗り換えたい・DWHから活用したい」という企業に向いていると説明されています。',
    source: 'QA表 No.114 / docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b16',
    text: 'Hightouchを使いこなすために、SQLやプログラミングの高度な知識は必ず必要ですか？',
    type: 'true_false',
    options: ['○ 必須。SQLなしでは使えない', '× 基本機能はノーコードで使える。SQLを書くとさらに柔軟に活用できる'],
    correctIndex: 1,
    explanation: 'Customer StudioはSQLなしで使えるノーコードUIです。ただし、DWHのモデル定義やカスタムセグメントにはSQLが役立ちます。マーケター向けの基本操作はSQLなしで完結します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b17',
    text: 'Hightouchのセグメントを作成しただけで（まだ同期を実行していない）、Sync数にカウントされますか？',
    type: 'true_false',
    options: ['○ セグメント作成時点でカウントされる', '× 実際にデータ同期（Sync実行）した時点からカウントされる'],
    correctIndex: 1,
    explanation: 'Hightouchの料金はActive Sync数（過去28日間で少なくとも1回実行されたSync数）に基づきます。セグメントを作るだけでは料金は発生しません。Syncを実行して初めてカウントされます。',
    source: 'QA表 No.87',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b18',
    text: 'HightouchはSOC 2 Type IIとISO 27001の認証を取得していますか？',
    type: 'true_false',
    options: ['○ 両方取得済み', '× どちらも取得していない'],
    correctIndex: 0,
    explanation: 'HightouchはSOC 2 Type IIとISO 27001の両方の認証を取得済みです。また、GDPR・CCPA・HIPAAにも対応しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b19',
    text: '「データウェアハウスをSingle Source of Truth（唯一の正となるデータ源）として使う」とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'DWHに保存されたデータを正として、そこから各ツールにデータを配信する',
      'DWHにあるすべてのデータを外部に公開する',
      'データを一つのツールだけに送る',
      'データウェアハウスを外部向けに開放する',
    ],
    correctIndex: 0,
    explanation: 'Single Source of Truthとは「DWHこそが最も正確・最新のデータ」という設計思想です。各ツールに散らばったデータをDWHに集約し、そこから正しいデータを各ツールに配信することで、データの一貫性が保たれます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b20',
    text: 'HightouchはDWHのデータを「保有・コピー」しますか？',
    type: 'true_false',
    options: ['○ Hightouchにデータをコピーして保管する', '× DWHのデータを読み取るだけで、Hightouch側にデータを永続保存しない'],
    correctIndex: 1,
    explanation: 'Hightouchのデータ非保存設計は重要なポイントです。データはDWHに置いたまま、必要な時だけ読み取って連携先ツールに送ります。Hightouch側にデータが溜まることはありません。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'basics',
  },
  {
    id: 'b21',
    text: '「Hightouchの管理レイヤー」があることのメリットとして正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'データを安く保管できる',
      'エラー確認・差分更新・スケジュール管理などデータ連携の運用を一元管理できる',
      'レポートが自動生成される',
      'ツールの契約管理ができる',
    ],
    correctIndex: 1,
    explanation: '「以前はCDPからSalesforceにデータが連携されていたが、失敗した原因が分からなかった」というような課題をHightouchは解決します。行単位のエラー確認・差分更新（全件再送不要）・スケジュール管理が一画面でできます。',
    source: 'QA表 No.128 / QA表 No.120',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b22',
    text: 'HightouchのBusinessプランでWorkspace（管理区画）はいくつ作れますか？',
    type: 'multiple_choice',
    options: [
      '最大3つまで',
      '最大10まで',
      '無制限に作成できる',
      '追加Workspaceには別途費用がかかる',
    ],
    correctIndex: 2,
    explanation: 'Businessプランではワークスペースを無制限に作成できます。グループ会社・部門・リージョン（日本/米国/欧州）などでWorkspaceを分けて管理することが可能です。',
    source: 'QA表 No.65',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b23',
    text: 'Hightouchを使うと「データの二重管理」が解消できるのはなぜですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchがデータを削除するから',
      'DWHのデータをそのまま各ツールに送るため、別のCDPにデータをコピーする必要がなくなるから',
      'Hightouchがデータを自動的に統合・圧縮するから',
      'クラウドが自動でデータを統合するから',
    ],
    correctIndex: 1,
    explanation: 'Treasure DataなどのパッケージCDPを使う場合、DWHにあるデータをCDPにも再投入する必要があり、データの二重管理が発生します。HightouchはDWHを直接参照するため、この問題がなくなります。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b24',
    text: 'Hightouchと直接契約するとどうなりますか？',
    type: 'multiple_choice',
    options: [
      '日本語サポートも含めて普通に使える',
      '技術的には可能だが、サポートは英語対応のみになる（DearOneのサポートなし）',
      '日本では直接契約が完全に不可能',
      '企業規模が大きくないと直接契約できない',
    ],
    correctIndex: 1,
    explanation: 'DearOneを通じず直接Hightouch社と契約することは技術的には可能ですが、QAサポート・契約関連の対応はすべて英語になります。DearOneを通じると日本語サポートが受けられます。',
    source: 'QA表 No.94',
    difficulty: 2,
    category: 'basics',
  },
  {
    id: 'b25',
    text: 'Hightouchの機能（Reverse ETL・Customer Studio・AI Decisioningなど）はすべてセットで購入しますか？',
    type: 'multiple_choice',
    options: [
      'すべてセットで購入する必要がある',
      '機能単位で選択して契約でき、追加で契約することもできる',
      '年間契約のみで月次変更は不可',
      'すべて無料で使える',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは機能単位（Reverse ETL / Customer Studio / AI Decisioning など）で選択して契約できます。まず必要な機能から始めて、追加の機能を後から契約することも可能です。',
    source: 'QA表 No.115',
    difficulty: 2,
    category: 'basics',
  },

  // ===== REVERSE ETL USECASE（20問） =====
  {
    id: 'u01',
    text: 'Hightouchが最も活用されるユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      '社内ドキュメントの全文検索',
      'DWHに蓄積した顧客データをMAツールや広告プラットフォームに自動配信',
      '社員の勤怠管理の自動化',
      '在庫管理の最適化',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの最も典型的なユースケースは「DWHに蓄積した顧客データをMoEngage・Salesforce・Google Adsなどに自動同期し、マーケティングに活用する」ことです。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u02',
    text: '「手動CSVアップロード」をHightouchで自動化するメリットとして正しくないものは？',
    type: 'multiple_choice',
    options: [
      '毎週・毎月の定型作業が自動化できる',
      '常に最新のデータで配信できる',
      '人的ミスがなくなる',
      '配信するメッセージの内容まで自動的に最適化される',
    ],
    correctIndex: 3,
    explanation: 'Hightouchはデータの同期・配信を自動化しますが、メール文面やクリエイティブの内容を自動最適化するものではありません（AI Decisioningは別の機能）。作業の自動化・データ鮮度の向上・ヒューマンエラーの防止が主なメリットです。',
    source: 'docs/competitors.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u03',
    text: 'Amplitude（分析ツール）単体では難しいことをHightouchを組み合わせると実現できます。それは何ですか？',
    type: 'multiple_choice',
    options: [
      'ユーザーの行動データを分析できる',
      'AmplitudeのセグメントをGoogle AdsやMoEngageなど他ツールに連携して活用できる',
      'リアルタイムのイベント計測ができる',
      'ダッシュボードや可視化レポートを作成できる',
    ],
    correctIndex: 1,
    explanation: 'AmplitudeはBIツールとして優秀ですが、そのセグメントを広告プラットフォームやMAツールに連携する機能は限られています。HightouchはDWHにあるAmplitudeのデータを各ツールに自由に連携できます。',
    source: 'QA表 No.113',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u04',
    text: 'Hightouchを使うと「差分更新」が可能になります。これはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      '毎回すべてのデータを送り直す（フルリフレッシュ）',
      '前回の同期から変更があったデータだけを送ることで、効率的に連携できる',
      'データを差し引き計算して送る',
      '古いデータを削除して新しいデータと置き換える',
    ],
    correctIndex: 1,
    explanation: '差分更新（Change Data Capture / CDC）により、前回のSync実行以降に変更・追加されたレコードのみを送ります。これにより処理時間の短縮とDWHへの負荷軽減が実現できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u05',
    text: '大量データ（例：1,000万件のユーザー）を連携する場合、Hightouchのパフォーマンスはどう影響を受けますか？',
    type: 'multiple_choice',
    options: [
      'Hightouchのサーバーが重くなりサービスが停止するリスクがある',
      '処理速度はデータソースであるDWH（Snowflake・BigQueryなど）のパフォーマンスに依存する',
      'データ量が多いほどHightouchの料金が急激に上昇する',
      '1億件以上のデータは処理できない',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの処理速度はDWH側のクエリ実行性能に依存します。日本の通信事業者で1日数千万行のデータをSnowflakeから各分析ツールに連携している実績もあります。',
    source: 'QA表 No.50 / QA表 No.26',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u06',
    text: '次のシナリオでHightouchが役立つのはどれですか？',
    type: 'multiple_choice',
    options: [
      '新しいデータウェアハウスを安く構築したい',
      '顧客の購買履歴データがSnowflakeにあり、それをMoEngageに同期してリターゲティングをしたい',
      '社内のSlackメッセージを翻訳したい',
      '従業員の人事評価システムを作りたい',
    ],
    correctIndex: 1,
    explanation: '「DWHにある購買データ → MoEngage/Braze/MA → リターゲティング」はHightouchの典型的なユースケースです。DWHのデータを起点に各マーケティングアクションを実行できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u07',
    text: 'DWHにある顧客データをSalesforceに同期するとき、Hightouchはどんな役割をしますか？',
    type: 'multiple_choice',
    options: [
      'SalesforceのCRM機能をDWHで置き換える',
      'DWHのデータを定期的に読み取り、Salesforceに自動反映するパイプラインを管理する',
      'SalesforceからDWHにデータを取り込む',
      'データを変換してCSVファイルを生成する',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWH→Salesforceの「パイプライン管理者」の役割を担います。設定したスケジュール・条件に従ってデータを自動同期し、Salesforceのリードや取引先情報を常に最新状態に保てます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u08',
    text: 'Hightouchを使うと、同期のエラー（例：特定のレコードが連携先ツールに入らなかった）はどのように確認できますか？',
    type: 'multiple_choice',
    options: [
      'エラーは手動でログファイルを調べる必要がある',
      '行（レコード）単位でリアルタイムにエラーを確認できる',
      'エラーが発生しても通知されない',
      'エラーは月1回のレポートで確認する',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの管理画面では、Sync実行ログを行単位で確認できます。「どのレコードが成功し、どのレコードが失敗したか・その理由」をリアルタイムに把握できます。',
    source: 'QA表 No.120',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u09',
    text: 'DWHのデータが整理されていない場合（例：複数テーブルに情報が分散している）、Hightouchは使えますか？',
    type: 'multiple_choice',
    options: [
      '使えない。DWHのデータが完全に整理されてから接続する必要がある',
      '使える。SQLを書いて複数テーブルを結合したデータをHightouchのモデルに設定できる',
      'Hightouchがデータを自動整理してくれる',
      '1テーブルのデータしか扱えない',
    ],
    correctIndex: 1,
    explanation: 'HightouchではSQL（クエリ）でデータを定義するため、複数テーブルをJOINしたデータや集計データも扱えます。「最終的に1つのキー（ユーザーID）で紐づければ」あとはSQLで対応できます。',
    source: 'QA表 No.127',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u10',
    text: 'ECサイト企業がHightouchを使う典型的なユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      '商品の自動発注管理',
      'DWHに蓄積した購買データからカート放棄ユーザーを抽出し、MAツールでリマーケティング',
      '倉庫の在庫管理最適化',
      '従業員の給与計算の自動化',
    ],
    correctIndex: 1,
    explanation: 'ECでの典型例は「カート放棄ユーザー・休眠顧客・高LTV顧客などをDWHのデータから抽出 → MoEngageやBrazeでプッシュ通知・メール配信」です。PetSmartでは6,500万人のロイヤリティ会員データを活用し増分売上15-25%増を実現しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u11',
    text: 'Hightouchで連携先ツール（Destination）として正式なコネクタがない場合でも連携できますか？',
    type: 'multiple_choice',
    options: [
      'できない。公式コネクタがないと使えない',
      'できる。REST APIを公開しているツールであればHTTP Requestデスティネーションで連携できる',
      'できるが、追加費用がかかる',
      'できるが、Hightouch社に個別開発を依頼する必要がある',
    ],
    correctIndex: 1,
    explanation: 'HightouchにはHTTP Requestというカスタムデスティネーション機能があります。KARTEなどの非公式コネクタでも、REST APIが公開されていれば連携が可能です。DearOneではSnowflake→KARTEの連携を検証済みです。',
    source: 'QA表 No.48 / QA表 No.96',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u12',
    text: 'HightouchはDWHにデータを書き戻す（DWHをDestinationとして使う）ことはできますか？',
    type: 'true_false',
    options: ['○ できる（SnowflakeやBigQueryをDestinationに設定できる）', '× できない（DWHはSourceのみ）'],
    correctIndex: 0,
    explanation: 'SnowflakeやBigQueryはSourceとしてだけでなく、Destinationとしても使えます。例えば「処理済みデータをDWHに書き戻す」ユースケースにも対応できます。',
    source: 'QA表 No.49',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u13',
    text: 'MAツール（例：MoEngage）の契約で「月間配信数の上限」がある場合、Hightouchではどう対処できますか？',
    type: 'multiple_choice',
    options: [
      '対処できない。Hightouchはすべてのデータを全件送信する',
      'Limit（件数制限）機能を使い、条件に合う上位N件のみを配信対象にできる',
      'MAツール側で制限する必要がある',
      'Syncを手動で停止する必要がある',
    ],
    correctIndex: 1,
    explanation: 'Hightouchには「Audience内の件数を上限Nまでに絞る」Limit機能や「TOP/BOTTOM Xパーセンタイル」機能があります。MAの配信上限に合わせてデータを絞り込んで送ることができます。',
    source: 'Hightouch公式ドキュメント（Limit機能）',
    difficulty: 3,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u14',
    text: '同じ顧客が広告・メール・LINEで重複して同じ配信を受けないようにするためにHightouchで使える機能はどれですか？',
    type: 'multiple_choice',
    options: [
      'Split（分割）機能',
      'Priority List（優先リスト）機能',
      'Match Booster機能',
      'Traits機能',
    ],
    correctIndex: 1,
    explanation: 'Priority List機能により「複数のAudienceに重複するユーザーがいる場合、どのAudience（＝施策）を優先するか」を設定できます。例えば「購買段階ごとのAudience A・B・Cで重複ユーザーは最も優先度の高いものだけに入れる」等の制御ができます。',
    source: 'QA表 No.57（類似ユースケース）',
    difficulty: 3,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u15',
    text: '「内製構築（社内エンジニアがスクリプトでデータ連携）」に対してHightouchが優れている点はどれですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchの方が必ず安い',
      '保守コストが低く、マーケターがセルフサービスで変更できる。新連携先の追加も開発不要',
      'Hightouchは完全ノーコードで何でもできる',
      '内製よりHightouchの方が常に処理が速い',
    ],
    correctIndex: 1,
    explanation: '内製構築の課題は「スクリプトの保守・エラー対応にエンジニアが張り付く・新連携先追加のたびに開発が必要・マーケター依頼のボトルネック」です。Hightouchはこれらをすべて解消できます。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u16',
    text: 'Hightouchを使った「広告パフォーマンス改善」の典型的なユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      '広告クリエイティブをAIが自動生成する',
      'DWHにある高LTV顧客データをGoogle AdsやMeta Adsに同期してターゲティング精度を高める',
      '広告予算を自動最適化する',
      '競合他社の広告を自動分析する',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWHの顧客データ（購買履歴・LTV・行動履歴等）をGoogle AdsやMeta Adsのカスタムオーディエンスに同期できます。LucidChartではこの手法でROAS +52%・工数95%削減を達成しています。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u17',
    text: 'HightouchでSync（データ連携）のスケジュールはどのように設定できますか？',
    type: 'multiple_choice',
    options: [
      '毎日決まった時間のみ設定できる',
      'リアルタイム・毎時・毎日・毎週など柔軟に設定でき、cron式での詳細設定も可能',
      '週1回のみ設定できる',
      'スケジュールは設定できず、手動実行のみ',
    ],
    correctIndex: 1,
    explanation: 'Hightouchのスケジュールは非常に柔軟で、リアルタイム・15分ごと・毎日特定の時間・特定の曜日など、cron式で細かく設定できます（例：「毎月第3月曜日」なども設定可能）。',
    source: 'QA表 No.85',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u18',
    text: 'HightouchでABテストを実施するためにどんな機能を使いますか？',
    type: 'multiple_choice',
    options: [
      'Filter機能でAとBのグループを別々に作る',
      'Split機能でAudienceを複数グループに分割し、それぞれ別のDestinationに送る',
      'Priority List機能でA/B優先順位を決める',
      'ABテストはHightouchの機能ではない',
    ],
    correctIndex: 1,
    explanation: 'Customer StudioのSplit機能を使うと、Audience内のユーザーを任意の比率で複数グループに分割できます。各グループを別々のSyncで異なるツール・設定に送ることでABテストを実施できます。',
    source: 'QA表 No.51（日本語）/ QA表 No.45（英語）',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u19',
    text: 'HightouchでPOC（概念実証）を実施する場合、通常どれくらいの期間が目安ですか？',
    type: 'multiple_choice',
    options: [
      '最低でも6ヶ月は必要',
      '1〜2週間程度で基本的な検証が可能。1ヶ月程度が一般的',
      '3ヶ月以上必要',
      '検証は本番導入後にしかできない',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは導入が早く、1〜2週間程度での基本的な検証が可能です。通常1ヶ月が目安で、無料アカウントで事前にトライしてからPOCに進む企業も多いです。',
    source: 'QA表 No.100',
    difficulty: 2,
    category: 'reverse_etl_usecase',
  },
  {
    id: 'u20',
    text: '「AIによるセグメントの自動生成・クラスタリング」はHightouchで可能ですか？',
    type: 'true_false',
    options: ['○ AIがセグメントを自動生成できる', '× セグメントの自動生成はできない。AI DecisioningはユーザーごとのAI最適化機能'],
    correctIndex: 1,
    explanation: 'Hightouchの「AI Decisioning」は「個々のユーザーに対して最適な次の行動を自動的に決定する」機能であり、「セグメントを自動生成する」機能ではありません。クラスタリングや類似オーディエンスの自動生成は提供していません。',
    source: 'QA表 No.126',
    difficulty: 3,
    category: 'reverse_etl_usecase',
  },

  // ===== CUSTOMER STUDIO（20問） =====
  {
    id: 'cs01',
    text: '「Customer Studio」とはHightouchのどんな機能ですか？',
    type: 'multiple_choice',
    options: [
      '顧客に請求書を発行する機能',
      'ノーコードでオーディエンス（セグメント）を作成・管理できるUI機能',
      '顧客とライブチャットをする機能',
      '社内顧客管理データベース',
    ],
    correctIndex: 1,
    explanation: 'Customer StudioはHightouchのノーコードUI機能です。SQLを書かなくても、条件を選択するだけで顧客セグメント（Audience）を作成できます。マーケターがセルフサービスでセグメントを管理できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs02',
    text: 'Customer Studioを使う主なユーザーはどんな人ですか？',
    type: 'multiple_choice',
    options: [
      'データエンジニアやデータサイエンティスト',
      'SQLを書けないマーケターやCRM担当者',
      '財務・経理担当者',
      'システム管理者のみ',
    ],
    correctIndex: 1,
    explanation: 'Customer StudioはノーコードUIのため、SQLの知識がなくても使えます。マーケター・CRM担当者・グロース担当者など、ビジネスサイドのメンバーが主なユーザーです。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs03',
    text: 'Customer StudioのAudience（オーディエンス）とは何ですか？',
    type: 'multiple_choice',
    options: [
      '配信するメール文章テンプレート',
      '特定の条件を満たすユーザーのグループ（セグメント）',
      '広告キャンペーンの設定',
      'ユーザーの行動ログファイル',
    ],
    correctIndex: 1,
    explanation: 'AudienceはCustomer Studioで作成するユーザーセグメントです。「過去30日以内に購入した」「累計購入額が1万円以上」などの条件でDWHのデータからユーザーグループを定義します。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs04',
    text: 'Customer Studioでエンジニアへの依頼なしに、マーケター自身がセグメントを作成・変更できますか？',
    type: 'true_false',
    options: ['○ できる', '× 最終確認だけエンジニアが必要'],
    correctIndex: 0,
    explanation: 'Customer StudioのノーコードUIにより、マーケターが直接「条件の追加・削除・変更」を行えます。エンジニアへの依頼なしにセグメントを素早く作成・修正でき、マーケティング施策のスピードが上がります。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs05',
    text: 'Customer Studioで作成したAudienceのサイズ（対象ユーザー数）はどこで確認できますか？',
    type: 'multiple_choice',
    options: [
      'Salesforceのレポートで確認',
      'Customer Studio内で「Calculate Size」ボタンを押すと確認できる',
      'DWHを直接クエリして確認する必要がある',
      '同期を実行しないとサイズが分からない',
    ],
    correctIndex: 1,
    explanation: 'Audience作成画面の「Calculate Size」ボタンを押すと、設定した条件に合うユーザーが何人いるかを事前に確認できます。同期を実行する前にセグメントの規模を把握できます。',
    source: 'QA表 No.59 / QA表 No.70',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs06',
    text: 'Customer Studioの「Traits（トレイツ）」機能とは何ですか？',
    type: 'multiple_choice',
    options: [
      '連携先ツールのメッセージテンプレート機能',
      'ユーザーに計算済み属性値（例：過去90日の合計購入金額）をコードなしで追加できる機能',
      'セグメントに名前・ラベルをつける機能',
      'データを暗号化するセキュリティ機能',
    ],
    correctIndex: 1,
    explanation: 'Traitsは「COUNT・SUM・MAX・MIN・AVERAGE」などの集計をノーコードで設定し、ユーザーの属性値として使えるようにする機能です。例：「過去90日のCV回数」「累計購入金額」などを属性として付加できます。',
    source: 'docs/hightouch-product.md / QA表 No.54',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs07',
    text: 'Customer StudioでAudienceをSplit（分割）する主な目的は何ですか？',
    type: 'multiple_choice',
    options: [
      'データを小さくして処理を速くするため',
      'ABテストのためにユーザーを複数グループ（コントロール・テスト等）に分けるため',
      'DWHのデータを複数の場所に分散保存するため',
      'Audienceを削除するため',
    ],
    correctIndex: 1,
    explanation: 'Splitは主にABテストや実験的な施策のために使います。Audience内のユーザーをA/B/C等の複数グループにランダム分割し、各グループに異なる施策を実施して効果を比較できます。',
    source: 'QA表 No.51 / QA表 No.55（英語）',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs08',
    text: 'Customer Studioの「Priority List（優先リスト）」機能の主な用途は何ですか？',
    type: 'multiple_choice',
    options: [
      'セグメントを優先順位付きで表示するだけのUI機能',
      '複数Audienceに重複するユーザーが存在する場合、どのAudienceを優先するかを設定する機能',
      '配信時刻を優先順位で決める機能',
      '重要な顧客に特別割引を自動適用する機能',
    ],
    correctIndex: 1,
    explanation: 'Priority Listは「1人のユーザーが複数のAudienceに同時に入っている場合、どのAudienceを優先して適用するか」を決める機能です。例えば「購入前の顧客・購入後1ヶ月の顧客・休眠顧客」のAudienceで重複を制御できます。',
    source: 'QA表 No.79',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs09',
    text: 'Customer Studioの「Performance」機能では何を確認できますか？',
    type: 'multiple_choice',
    options: [
      'Hightouchサーバーの稼働状況・レスポンス速度',
      '時間軸に沿ったAudienceサイズの変化や、目標イベントの発生数',
      '配信したメールの開封率・クリック率',
      '広告のCPAやROAS（広告費用対効果）',
    ],
    correctIndex: 1,
    explanation: 'Performance機能はAmplitudeのセグメンテーションチャートに相当します。Audienceのユーザー数の増減・目標イベント（CV等）の発生状況を時系列で追跡できます。Lightning Sync Engineが必要です。',
    source: 'QA表 No.56 / QA表 No.7（英語）',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs10',
    text: 'Customer StudioでAudienceを作成するとき、その結果データは最終的にどこに送られますか？',
    type: 'multiple_choice',
    options: [
      'Hightouchのデータベースに永続保存される',
      '設定したSyncによってMoEngage・Google Adsなどの連携先ツールに送られる',
      'メールで担当者に自動送信される',
      'Excel/CSVファイルとしてダウンロードされる',
    ],
    correctIndex: 1,
    explanation: 'AudienceはCustomer Studioで定義するだけでは何も起きません。SyncでDestinationを設定し、実際に同期を実行することでMoEngage・Google Ads・Brazeなどの連携先にデータが送られます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs11',
    text: 'Customer Studioで「イベントデータ」（例：商品閲覧・カート追加イベント）は条件として使えますか？',
    type: 'true_false',
    options: ['○ 使える（SchemaでイベントテーブルをRelated Modelとして設定すれば使用可能）', '× 使えない（プロフィールデータのみ）'],
    correctIndex: 0,
    explanation: 'Customer StudioのSchemaでイベントテーブルをRelated Modelとして設定することで、イベントデータを条件に使えます。例えば「過去30日以内にカートに商品を追加したが購入していないユーザー」などのセグメントが作れます。',
    source: 'QA表 No.52',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs12',
    text: 'troccoとHightouchを比較したとき、Customer Studioのようなマーケター向けのセルフサービスUIはtroccoにありますか？',
    type: 'true_false',
    options: ['○ ある（troccoも同様のUIを持っている）', '× ない（troccoはエンジニア向けのETLツールで、Audience構築UIはない）'],
    correctIndex: 1,
    explanation: 'troccoはエンジニア向けのETL/リバースETLツールであり、マーケターがGUIで直接セグメントを作成するCustomer Studioのような機能はありません。これがHightouchの最大の差別化ポイントの一つです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs13',
    text: 'Hightouchの「AI Decisioning（AIディシジョニング）」とはどんな機能ですか？',
    type: 'multiple_choice',
    options: [
      'AIがAudience（セグメント）条件を自動生成する機能',
      'AIが個々のユーザーに最適なメッセージ・チャネル・タイミングを自動で決定する、Customer Studioとは独立した機能',
      'AIが広告クリエイティブを自動生成する機能',
      'AIが最適なデータウェアハウスを選択する機能',
    ],
    correctIndex: 1,
    explanation: 'AI Decisioning（AID）はCustomer Studioとは別の独立した製品です。「1対1のパーソナライズ最適化」を担い、メールを送るか・プッシュ通知を送るか・いつ送るかをユーザーごとにAIが自動で最適化します。WHOOPでは6週間でCV +10%の成果を出しています。',
    source: 'Hightouch公式ドキュメント（https://hightouch.com/docs/ai-decisioning/overview）',
    difficulty: 3,
    category: 'basics',
  },
  {
    id: 'cs14',
    text: 'Customer StudioでAudienceの条件に使える集計（COUNT・SUMなど）を設定するのはどの機能ですか？',
    type: 'multiple_choice',
    options: [
      'Filter機能',
      'Schema機能',
      'Traits機能',
      'Split機能',
    ],
    correctIndex: 2,
    explanation: 'Traitsで「過去30日のCV数（COUNT）」「累計購入金額（SUM）」「最後の購入日（MAX）」などの集計値をユーザー属性として定義し、Audienceの条件に使えるようにします。',
    source: 'QA表 No.54 / QA表 No.80',
    difficulty: 2,
    category: 'customer_studio',
  },
  {
    id: 'cs15',
    text: 'Customer Studioの「Breakdown（内訳）」機能を使うとどんな分析ができますか？',
    type: 'multiple_choice',
    options: [
      'Audienceの会員属性別（性別・年齢帯・地域など）の構成比を確認できる',
      'データをアルファベット順に並べ替えられる',
      'DWHのテーブル構造を分析できる',
      '月別の売上推移を確認できる',
    ],
    correctIndex: 0,
    explanation: 'Breakdown機能は、作成したAudienceを特定の属性（性別・年齢帯・購買カテゴリなど）で分けた場合の構成比を確認できます。AmplitudeのUser Compositionチャートに相当します。',
    source: 'QA表 No.56',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs16',
    text: 'Customer Studioで「個人情報カラム」をUI上で非表示にするセキュリティ機能は何ですか？',
    type: 'multiple_choice',
    options: [
      'Encrypt（暗号化）機能',
      'Redact（リダクト）機能',
      'Private（プライベート）モード',
      'Shield（シールド）機能',
    ],
    correctIndex: 1,
    explanation: 'Redact機能を使うと、特定カラムの値をHightouch UI上でマスク（非表示）にできます。氏名・メールアドレスなどの個人情報を表示させずに、安全にAudienceの構築・確認ができます。',
    source: 'QA表 No.5',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs17',
    text: 'Customer Studioで「Audienceを保存するだけ（Syncを設定しない）」でもデータ連携はされますか？',
    type: 'true_false',
    options: ['○ される（Audienceを保存するとデータが送られる）', '× されない（SyncでDestinationを設定・実行して初めてデータが送られる）'],
    correctIndex: 1,
    explanation: 'Audienceの定義を保存するだけではデータは何も送られません。Syncを別途設定し、スケジュールまたは手動で実行することでDestinationにデータが送られます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs18',
    text: 'Customer Studioでセグメントを作成できる件数に上限はありますか？',
    type: 'true_false',
    options: ['○ 上限がある（最大100件まで）', '× 上限はない（制限なく作成できる）'],
    correctIndex: 1,
    explanation: 'Hightouchではソース・デスティネーション・シート数・セグメント数などの上限はありません。課金に影響するのはActive Sync数（実行したSync数）のみです。',
    source: 'QA表 No.13（英語版）',
    difficulty: 1,
    category: 'customer_studio',
  },
  {
    id: 'cs19',
    text: 'Customer Studioの「Schema（スキーマ）」設定とはどういう意味ですか？',
    type: 'multiple_choice',
    options: [
      'データを外部に公開するための設定',
      'Customer Studioで使うデータのテーブル構造（どのテーブルがどう関連するか）を定義する設定',
      'データの暗号化スキームを設定する',
      '配信スケジュールを設定する',
    ],
    correctIndex: 1,
    explanation: 'Schemaではデータモデルの構造（Parent Model・Related Model・Event Modelの関係性）を定義します。これにより、Customer Studioで「顧客情報テーブル」と「購買履歴テーブル」などを結びつけて条件として使えるようになります。',
    source: 'QA表 No.59',
    difficulty: 3,
    category: 'customer_studio',
  },
  {
    id: 'cs20',
    text: 'Customer Studioは「Customer Studio（セグメント構築）」と「Reverse ETL（Sync設定）」どちらか片方だけ使うことはできますか？',
    type: 'true_false',
    options: ['○ できる（それぞれ独立して契約・利用できる）', '× できない（セットで使わないといけない）'],
    correctIndex: 0,
    explanation: 'HightouchはReverse ETLとCustomer Studioを別々に契約して利用できます。例えば「Reverse ETLのみ」契約して、後から「Customer Studio」を追加することも可能です。',
    source: 'QA表 No.115',
    difficulty: 2,
    category: 'customer_studio',
  },

  // ===== WORKSPACE MANAGEMENT（10問） =====
  {
    id: 'ws01',
    text: 'Hightouchの「Workspace（ワークスペース）」とは何ですか？',
    type: 'multiple_choice',
    options: [
      'チームメンバーが作業するオフィス名',
      'ブランドや部門・リージョンごとにデータ連携設定を分けるHightouchの管理単位',
      'データを一時保管するストレージ',
      'ダッシュボードやレポートを共有する機能',
    ],
    correctIndex: 1,
    explanation: 'Workspaceはブランド・部門・リージョン（日本/US/EU）などを分けて管理するための区画です。Workspaceごとに独立したSource・Destination・Sync・ユーザー権限を持てます。',
    source: 'QA表 No.28',
    difficulty: 1,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws02',
    text: '複数のグループ会社でHightouchを利用する場合、Workspaceの扱いはどうなりますか？',
    type: 'multiple_choice',
    options: [
      'すべてのグループ会社を一つのWorkspaceで管理しなければならない',
      'グループ会社ごとに別々のWorkspaceを作成できるが、それぞれ別途ライセンス契約が必要',
      'BusinessプランならWorkspaceを無制限に作成でき、同一ライセンス内で複数グループ会社に対応できる',
      'グループ会社での共有は不可能',
    ],
    correctIndex: 1,
    explanation: 'Businessプランでは同一法人内であれば無制限のWorkspace作成が可能です。ただし、別グループ会社（別法人）での利用は別途ライセンス契約が必要です。WorkspaceはあくまでHightouchの管理単位であり、契約はグループ会社単位になります。',
    source: 'QA表 No.65 / QA表 No.83',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws03',
    text: 'Hightouchでシングルサインオン（SSO）を使うには何が必要ですか？',
    type: 'multiple_choice',
    options: [
      '無料プランでも使える',
      'BusinessプランまたはEnterprise相当のプランへの加入が必要',
      'SSOは現在非対応',
      'エンジニアが自社でSAML認証サーバーを構築する必要がある',
    ],
    correctIndex: 1,
    explanation: 'SSOはHightouchのBusinessプランに含まれる機能です。SAML SSO（Okta・Azure ADなど）に対応しており、Businessプラン契約後に利用できます。',
    source: 'QA表 No.86',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws04',
    text: '1つのSyncを複数のWorkspaceで共有して使うことはできますか？',
    type: 'true_false',
    options: ['○ できる', '× できない（Workspaceごとに個別にSyncを作成する必要がある）'],
    correctIndex: 1,
    explanation: '現状、SyncはWorkspaceをまたいで共有できません。同じ設定のSyncが複数Workspaceで必要な場合は、それぞれのWorkspaceで個別に作成する必要があります。それぞれのSyncがActive Sync数にカウントされます。',
    source: 'QA表 No.69',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws05',
    text: 'Hightouchの利用ユーザー数（アカウント数）が増えた場合、追加費用はかかりますか？',
    type: 'true_false',
    options: ['○ かかる（アカウント数に応じて費用が増える）', '× かからない（アカウント数は課金対象外）'],
    correctIndex: 1,
    explanation: 'Hightouchの課金対象はActive Sync数のみです。アカウント数・シート数・ユーザー数は費用に影響しません。部門を増やしてもHightouchの費用は変わりません。',
    source: 'QA表 No.22',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws06',
    text: 'Hightouchの変更履歴管理（バージョン管理）はどの機能で実現できますか？',
    type: 'multiple_choice',
    options: [
      '管理画面の「変更履歴」タブ',
      'GitとのSync連携によるバージョン管理機能',
      '変更履歴の管理機能はない',
      'Audit Logのダウンロード機能',
    ],
    correctIndex: 1,
    explanation: 'HightouchはGitとの連携機能を持っており、Syncの設定をGitで管理できます。これによりSyncやModelの変更履歴管理・ロールバック・コードレビューが可能になります。',
    source: 'QA表 No.90',
    difficulty: 3,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws07',
    text: 'Hightouchにログインする際に使える認証方式として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'ID/パスワードのみ',
      'Google/Microsoft SSO、メールアドレス認証、SAML SSO（Okta等）に対応',
      'Googleアカウントのみ',
      '多要素認証（MFA）は非対応',
    ],
    correctIndex: 1,
    explanation: 'Hightouchのログイン方法はメールアドレス認証・Google/Microsoft SSO・SAML SSO（Okta・Azure ADなど）の複数方式に対応しています。パスワード要件はそれぞれの認証サービス側の設定に依存します。',
    source: 'QA表 No.29（英語）',
    difficulty: 2,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws08',
    text: '「カスタムロール（Custom Role）」を作成する主な目的は何ですか？',
    type: 'multiple_choice',
    options: [
      'アプリの見た目・テーマをカスタマイズするため',
      '部門・役割に応じてアクセスできる機能を制限し、セキュリティとガバナンスを強化するため',
      '連携先ツールへのアクセス権を外部管理するため',
      '課金プランを自動的に変更するため',
    ],
    correctIndex: 1,
    explanation: 'カスタムロールを使うと「この部門のユーザーはSourceの閲覧のみ可・Syncの変更は不可」のような細かい権限設定ができます。大企業でのセキュリティ・コンプライアンス要件に対応できます。',
    source: 'QA表 No.30',
    difficulty: 3,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws09',
    text: '検証用・テスト用Workspaceで実行したSyncはActive Sync数にカウントされますか？',
    type: 'true_false',
    options: ['○ カウントされる（検証用でも実際に同期実行するとカウントされる）', '× カウントされない'],
    correctIndex: 0,
    explanation: '検証・テスト目的であっても、Syncを実際に実行するとActive Sync数にカウントされます。本番とは別の検証用Workspaceでの実行も同様です。テスト専用の無課金ワークスペース機能は標準ではありません。',
    source: 'QA表 No.82',
    difficulty: 3,
    category: 'workspace_mgmt',
  },
  {
    id: 'ws10',
    text: 'Workspaceを削除したい場合はどうしますか？',
    type: 'multiple_choice',
    options: [
      'Workspace設定画面から自分で削除できる',
      'Hightouch社に依頼して対応してもらう必要がある',
      'DearOneに削除を依頼する',
      '削除は不可能で、非アクティブ状態にするしかない',
    ],
    correctIndex: 1,
    explanation: 'WorkspaceはHightouch社に削除を依頼する必要があります（セルフサービスで削除できません）。誤って必要なWorkspaceを消してしまわないよう、この仕様になっています。',
    source: 'QA表 No.71',
    difficulty: 2,
    category: 'workspace_mgmt',
  },

  // ===== INTEGRATIONS（10問） =====
  {
    id: 'int01',
    text: 'HightouchとAmplitudeを組み合わせると何ができますか？',
    type: 'multiple_choice',
    options: [
      'AmplitudeのダッシュボードをHightouchで表示できる',
      'DWHにあるユーザーデータをGoogle AdsやMoEngageなど他ツールに連携できる',
      'Amplitudeの分析機能がHightouchに統合される',
      'AmplitudeのイベントをリアルタイムでSalesforceに送れる',
    ],
    correctIndex: 1,
    explanation: 'Amplitude単体では分析・セグメントの作成ができますが、そのセグメントを広告や他のMAに送る機能は限られています。HightouchはDWHにあるデータを活用し、Amplitudeのセグメントを各ツールに連携できます。',
    source: 'QA表 No.113',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int02',
    text: 'HightouchとMoEngageを連携させると何ができますか？',
    type: 'multiple_choice',
    options: [
      'MoEngageの管理画面をHightouchから操作できる',
      'DWHにある顧客セグメントをMoEngageに同期し、プッシュ通知・メール配信に活用できる',
      'MoEngageのデータをDWHに取り込める',
      'MoEngageの配信コストが削減される',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは「DWH → MoEngage（ユーザー属性・セグメントの同期）」のパイプラインを管理します。MoEngage側では最新の顧客データを使ったセグメント配信・パーソナライズ配信ができます。',
    source: 'docs/hightouch-product.md',
    difficulty: 1,
    category: 'integrations',
  },
  {
    id: 'int03',
    text: 'Google広告系でHightouchが標準コネクタで連携できるサービスはどれですか？',
    type: 'multiple_choice',
    options: [
      'Google Analytics・Google Search Console',
      'Google Ads・Google Ad Manager 360（有料版）',
      'Google Chrome・Google Drive・Gmail',
      'Google Cloud・Kubernetes Engine',
    ],
    correctIndex: 1,
    explanation: 'HightouchはGoogle Adsと連携してカスタムオーディエンスを同期できます。Google Ad Manager 360（GAM 360）はBusinessプランのみ対応です。無料版のGoogle Ad Managerは対応外です。',
    source: 'QA表 No.46 / QA表 No.47',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int04',
    text: 'HightouchのコネクタリストにないツールとHightouchを連携する方法は？',
    type: 'multiple_choice',
    options: [
      '連携は不可能',
      '「HTTP Request」デスティネーションを使い、REST APIで連携できる',
      'Hightouch社に有料カスタム開発を依頼する',
      'DearOneがすべてのツール向けのカスタムコネクタを無償で開発する',
    ],
    correctIndex: 1,
    explanation: 'HTTP RequestデスティネーションはJSON形式でREST APIにデータを送る汎用コネクタです。APIを公開しているツールであればほぼ連携できます。DearOneではKARTEとの連携を検証済みです。',
    source: 'QA表 No.48 / QA表 No.96',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int05',
    text: 'HightouchはTreasure Dataとの公式コネクタを持っていますか？',
    type: 'true_false',
    options: ['○ ある', '× ない（現時点でTreasure Dataとの公式コネクタはない）'],
    correctIndex: 1,
    explanation: 'Hightouchには現在Treasure Data向けの公式コネクタはありません。HTTP Request経由での連携も、Treasure Data側のAPIが限定的なため容易ではありません。',
    source: 'QA表 No.88',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int06',
    text: 'HightouchでSnowflakeを使う場合、SourceとDestinationのどちらに使えますか？',
    type: 'multiple_choice',
    options: [
      'Sourceとしてのみ使える',
      'Destinationとしてのみ使える',
      'SourceとDestinationの両方として使える',
      'Snowflakeはコネクタに含まれていない',
    ],
    correctIndex: 2,
    explanation: 'Snowflakeは「DWHからデータを読む（Source）」としても、「処理済みデータをDWHに書き戻す（Destination）」としても使えます。BigQueryやDatabricksも同様です。',
    source: 'QA表 No.49',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int07',
    text: 'HightouchはAirflow（ワークフローツール）と連携できますか？',
    type: 'true_false',
    options: ['○ できる（HightouchのSyncをAirflowのワークフローに組み込めるOperatorが提供されている）', '× できない'],
    correctIndex: 0,
    explanation: 'HightouchはAirflow・Prefect・Airbyteなど外部ワークフローツールとの連携機能を提供しています。データパイプラインのオーケストレーションに組み込めます。',
    source: 'QA表 No.95 / QA表 No.97',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int08',
    text: 'VWO（Visual Website Optimizer）を使っているマーケターにとってHightouchはどう役立ちますか？',
    type: 'multiple_choice',
    options: [
      'VWOのABテストをHightouchが自動実行する',
      'DWHにある顧客属性データをVWOに送り、パーソナライズテストに活用できる',
      'VWOのヒートマップ分析をHightouchで実行できる',
      'VWOはHightouchと互換性がない',
    ],
    correctIndex: 1,
    explanation: 'HightouchのDestinationにはVWOも含まれています。DWHにある顧客セグメント（高LTV・新規・休眠等）をVWOに送ることで、セグメントベースのパーソナライズテストが実施できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int09',
    text: 'HightouchのSync実行速度（処理時間）に最も影響する要因は何ですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchのサーバースペック',
      'SourceであるDWH（Snowflake・BigQueryなど）のクエリ実行パフォーマンス',
      'インターネット回線速度',
      '連携先ツールのAPI制限',
    ],
    correctIndex: 1,
    explanation: 'HightouchはDWH側でデータを処理・抽出した後に連携先に送ります。そのため処理速度はDWHのクエリ性能に大きく依存します。DWH側のリソースを増やすことで高速化できます（Lightning Sync Engine利用時）。',
    source: 'QA表 No.50 / QA表 No.64',
    difficulty: 2,
    category: 'integrations',
  },
  {
    id: 'int10',
    text: 'HightouchはdbtやFivetranなどのデータ変換・取り込みツールとどんな関係にありますか？',
    type: 'multiple_choice',
    options: [
      '競合関係にある',
      '補完関係にある（dbtでDWHのデータを整形→HightouchでMAや広告に送るという組み合わせが一般的）',
      'Hightouchがdbtを内蔵している',
      '連携できない',
    ],
    correctIndex: 1,
    explanation: 'dbtはDWH内のデータ変換（SQL変換・モデリング）、FivetranはデータをDWHに取り込む（ETL）ツールです。Hightouchはその後段で「DWH → マーケティングツール」の役割を担い、これらのツールと連携して使われます。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'integrations',
  },

  // ===== COMPETITORS（10問） =====
  {
    id: 'cp01',
    text: 'Treasure DataとHightouchの最大の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'Treasure Dataは日本語非対応でHightouchは日本語対応',
      'Treasure DataはCDP独自基盤にデータを保有するが、HightouchはDWHのデータをそのまま活用する',
      'HightouchはTreasure Dataより機能が少ない',
      'Treasure Dataは広告連携に特化、HightouchはCRM連携に特化している',
    ],
    correctIndex: 1,
    explanation: 'Treasure Dataは自社クラウドにデータを保存するパッケージ型CDPです。Hightouchは既存DWHのデータをそのまま活用するため、データのコピー・二重管理が不要です。これが最大の設計思想の違いです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp02',
    text: 'Treasure Dataの料金モデルの特徴として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'Sync本数で課金される（Hightouchと同じ）',
      'データ投入量・保持プロファイル数に応じて課金され、ユーザー規模が大きいほど費用が増加する',
      '月額固定料金で使い放題',
      'APIコール数で課金される',
    ],
    correctIndex: 1,
    explanation: 'Treasure Dataはデータ量・プロファイル数課金のため、ユーザー数が増えるほど費用も増加します。一方HightouchはSync本数課金のため、ユーザーが増えても費用は変わりません。これは成長企業にとって大きな違いです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp03',
    text: 'troccoがHightouchより強みを持つ領域はどれですか？',
    type: 'multiple_choice',
    options: [
      'マーケター向けのセグメント構築ノーコードUI',
      'ETL（データをDWHに取り込む）機能',
      '広告プラットフォームへの連携数',
      'AI最適化・AI Decisioning機能',
    ],
    correctIndex: 1,
    explanation: 'troccoはETL（外部データをDWHに集める）の機能が強く、日本語対応でエンジニアに使いやすいツールです。一方HightouchはリバースETL（DWH→各ツール）とマーケター向けUI（Customer Studio）が強みです。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp04',
    text: 'Hightouchとtroccoはどのような役割分担が可能ですか？',
    type: 'multiple_choice',
    options: [
      'troccoはHightouchの上位互換なので役割分担は不要',
      'ETL（データ取り込み）はtrocco、リバースETL（データ活用・配信）はHightouchで棲み分けできる',
      'troccoはHightouchと統合予定',
      'Hightouchはtroccoと公式パートナーシップを持つ',
    ],
    correctIndex: 1,
    explanation: 'troccoとHightouchは競合しながらも共存できます。「troccoで外部データをDWHに集め、HightouchでDWHのデータをMAや広告に配信する」という棲み分けは実際の導入パターンとして存在します。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp05',
    text: '「手動CSV運用」からHightouchへ移行した場合に最も期待できる効果はどれですか？',
    type: 'multiple_choice',
    options: [
      'データの量が自動的に増える',
      '毎週・毎月の手動作業がなくなり、常に最新データで自動配信できるようになる',
      '配信コストが0円になる',
      'ツールの機能サポートが充実する',
    ],
    correctIndex: 1,
    explanation: '手動CSV運用の課題は「定型作業の工数・データが古くなる・ヒューマンエラー」です。Hightouchに移行すると自動化・最新データ・エラーなしが実現できます。',
    source: 'docs/competitors.md',
    difficulty: 1,
    category: 'competitors',
  },
  {
    id: 'cp06',
    text: 'HightouchがSegmentと比較して最大の設計上の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'HightouchはSegmentより価格が安い',
      'HightouchはDWHを中核とするComposable CDPアーキテクチャを採用し、データをコピーしない',
      'HightouchはSegmentの機能を包含している',
      'SegmentはHightouchより連携先が少ない',
    ],
    correctIndex: 1,
    explanation: 'SegmentはデータをSegment側に集める仕組みですが、HightouchはDWHをそのままCDPとして使うComposable CDPアーキテクチャです。HightouchはSegmentの創業エンジニアがDWH中心に再設計したツールと言えます。',
    source: 'QA表 No.116',
    difficulty: 3,
    category: 'competitors',
  },
  {
    id: 'cp07',
    text: 'HightouchのSync本数課金がTreasure Data（プロファイル数課金）より成長企業に有利な理由は？',
    type: 'multiple_choice',
    options: [
      'Hightouchは常に安いから',
      'HightouchはSync本数課金のため、ユーザー数・データ量が増えても追加費用が発生しないから',
      'Hightouchは無制限プランを提供しているから',
      'Treasure Dataの品質が劣るから',
    ],
    correctIndex: 1,
    explanation: 'プロファイル数課金では「ユーザーが増える＝費用が増える」という構造になります。Hightouchはユーザー数・データ量が増えても課金はSyncの本数だけに依存するため、スケールしても費用が跳ね上がりません。',
    source: 'docs/competitors.md',
    difficulty: 3,
    category: 'competitors',
  },
  {
    id: 'cp08',
    text: '「パッケージ型CDP（Treasure DataやSegment）」を使うとデータ管理で発生しやすい課題はどれですか？',
    type: 'multiple_choice',
    options: [
      'データが暗号化されない',
      'DWHとCDP間でデータの二重管理・鮮度の問題が発生しやすい',
      'データが自動削除される',
      'ユーザー数に厳しい制限がある',
    ],
    correctIndex: 1,
    explanation: 'パッケージ型CDPではDWHのデータをCDPに再投入（コピー）する必要があり、「どちらが最新か分からない」「同期のタイムラグで鮮度が落ちる」「管理工数が2倍になる」などの課題が発生します。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp09',
    text: 'Hightouchに向いている企業・状況として最も正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'まだデータウェアハウスを持っていない企業',
      'CDPがない・既存システムを乗り換えたい・DWHを持っているがマーケティング活用できていない企業',
      '広告だけに活用したい企業',
      '大企業のみ（中小企業は不向き）',
    ],
    correctIndex: 1,
    explanation: 'QA表でも「CDPがない・既存システムから乗り換えたい・DWHと一緒に構築したい」企業に向いていると説明されています。DWHを既に持っているが活用できていない企業が最も典型的なターゲットです。',
    source: 'QA表 No.114',
    difficulty: 2,
    category: 'competitors',
  },
  {
    id: 'cp10',
    text: '「内製構築（スクリプトによるデータ連携）」の主なデメリットとして正しくないものはどれですか？',
    type: 'multiple_choice',
    options: [
      'エラー発生時のデバッグにエンジニアが張り付く必要がある',
      '新しい連携先が増えるたびに開発工数が必要',
      'データ処理速度が必ずHightouchより遅くなる',
      'マーケターがセグメントを変えたいときにエンジニアへの依頼が必要',
    ],
    correctIndex: 2,
    explanation: '内製構築のデメリットは「保守コスト・拡張コスト・マーケターのボトルネック・エラー管理の難しさ」です。処理速度は内製でも高速に実装できるため、速度が必ずHightouchより劣るわけではありません。',
    source: 'docs/competitors.md',
    difficulty: 2,
    category: 'competitors',
  },

  // ===== SECURITY（5問） =====
  {
    id: 'sec01',
    text: 'Hightouchのデータセキュリティに関する最大の特徴はどれですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchは顧客データを自社サーバーに永続保存して管理する',
      'DWHからデータを読み取るだけで、Hightouch側にデータを永続保存しない「データ非保存設計」',
      'データはHightouch社が独自に暗号化して管理する',
      'セキュリティはDWH側の責任で、Hightouchは関与しない',
    ],
    correctIndex: 1,
    explanation: 'Hightouchの重要な設計思想が「データ非保存」です。DWHからデータを読み取ってDestinationに送りますが、Hightouch側にデータを永続保存しません。これにより個人情報の漏洩リスクを最小化します。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'security',
  },
  {
    id: 'sec02',
    text: 'HightouchはGDPRやHIPAA（医療情報保護法）に対応していますか？',
    type: 'true_false',
    options: ['○ GDPR・CCPA・HIPAAのすべてに対応している', '× HIPAAには非対応'],
    correctIndex: 0,
    explanation: 'HightouchはGDPR（EU一般データ保護規則）・CCPA（カリフォルニア州消費者プライバシー法）・HIPAA（米国医療情報保護法）のすべてに対応しています。医療系企業への提案でも対応可能です。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'security',
  },
  {
    id: 'sec03',
    text: 'HightouchがデータをDWHから読み取る際の通信暗号化プロトコルは何ですか？',
    type: 'multiple_choice',
    options: [
      'HTTP（暗号化なし）',
      'TLS 1.2以上',
      'SSHトンネル',
      'FTP',
    ],
    correctIndex: 1,
    explanation: 'HightouchはTLS 1.2以上での通信暗号化を使用しています。また、AWS PrivateLinkやGCP Private Service Connectを使った閉域網接続にも対応しており、より高いセキュリティが求められる場合に選択できます。',
    source: 'docs/hightouch-product.md',
    difficulty: 3,
    category: 'security',
  },
  {
    id: 'sec04',
    text: 'Hightouchが取得しているセキュリティ認証として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'ISO 9001・PCI DSS',
      'SOC 2 Type II・ISO 27001',
      'JIS Q 27001のみ',
      'HIPAA認定・FedRAMP',
    ],
    correctIndex: 1,
    explanation: 'HightouchはSOC 2 Type II（米国の情報セキュリティ監査）とISO 27001（国際標準のISMS認証）の両方を取得済みです。エンタープライズ・金融・医療系の企業への提案時に有効な証明です。',
    source: 'docs/hightouch-product.md',
    difficulty: 2,
    category: 'security',
  },
  {
    id: 'sec05',
    text: 'Hightouchを使うと、Customer Studio上で個人情報（氏名・メールアドレス）のカラム値を非表示にすることはできますか？',
    type: 'true_false',
    options: ['○ できる（Redact機能でUI上の値を非表示にできる）', '× できない'],
    correctIndex: 0,
    explanation: 'Customer StudioのRedact（リダクト）機能を使うと、特定カラムの値をHightouch UI上でマスクできます。セキュリティ上の観点から、個人情報（PII）カラムをマーケターに見せずにセグメント構築できます。',
    source: 'QA表 No.5',
    difficulty: 3,
    category: 'security',
  },

  // ===== AWS・GCP基礎 + Hightouch連携（20問） =====
  {
    id: 'cld01',
    text: 'Amazon RedshiftをHightouchのSourceとして使う場合、HightouchはどのようにRedshiftに接続しますか？',
    type: 'multiple_choice',
    options: [
      'Redshiftのスナップショット（バックアップ）を経由してデータを取得する',
      'JDBC接続でRedshiftに直接クエリを実行し、クエリ結果をSyncに使用する',
      'S3にエクスポートしたデータをHightouchが読み込む',
      'AWS DataSyncを経由してデータを転送する',
    ],
    correctIndex: 1,
    explanation: 'HightouchはRedshiftにJDBC（Java Database Connectivity）接続でSQLクエリを実行し、その結果をSyncに使用します。HightouchのネットワークからのアクセスをIP許可リストに設定し、専用ユーザーへの読み取り権限付与が必要です。',
    source: 'Hightouch公式ドキュメント（Amazon Redshift Source）',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld02',
    text: 'BigQueryをHightouchのSourceとして接続する際、推奨される認証方式はどれですか？',
    type: 'multiple_choice',
    options: [
      'GCPのルートアカウントのAPIキーを使う',
      'Googleアカウントのパスワードを直接設定する',
      'Hightouch専用のGCPサービスアカウントを作成し、必要最小限の権限を付与する',
      'BigQueryの公開データセット機能を有効化する',
    ],
    correctIndex: 2,
    explanation: 'BigQueryとHightouchの接続には、GCPのサービスアカウント（Service Account）を使用します。サービスアカウントに「BigQuery Data Viewer」「BigQuery Job User」などの最小限の権限を付与し、そのJSON鍵ファイルをHightouchに設定します。最小権限の原則（Principle of Least Privilege）を守ることがセキュリティ上重要です。',
    source: 'Hightouch公式ドキュメント（BigQuery Source）',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld03',
    text: 'BigQueryのパーティションテーブルをHightouchのModelクエリで活用するとどのようなメリットがありますか？',
    type: 'multiple_choice',
    options: [
      'パーティションテーブルはHightouchでは使えない',
      'クエリがパーティション単位に絞られるため、スキャン量が減りBigQueryのコストと実行時間を削減できる',
      'パーティションテーブルを使うと自動的にHightouchのSync速度が2倍になる',
      'パーティションテーブルは読み取り専用のため、HightouchのSync先には使えない',
    ],
    correctIndex: 1,
    explanation: 'BigQueryのパーティションテーブルに対してWHERE句でパーティション列を絞り込むと、スキャン対象のデータ量が大幅に減少します。例えば「WHERE updated_at >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY)」とすると直近7日分のデータのみスキャンされ、コストと速度が改善します。HightouchのModelクエリでこの絞り込みを活用することを推奨します。',
    source: 'Hightouch公式ドキュメント（BigQuery最適化）',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld04',
    text: 'HightouchをAmazon Redshiftに接続する際のセキュリティ上の推奨設定として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'RedshiftのクラスターをパブリックアクセスONにし、インターネット経由でHightouchから接続する',
      'HightouchのIPアドレス範囲のみを許可するSecurity Group設定をRedshiftに追加する',
      'Redshiftのmasterユーザー（admin）の認証情報をHightouchに設定する',
      'Redshiftのデータを全てS3にコピーしてからHightouchに読み込ませる',
    ],
    correctIndex: 1,
    explanation: 'Hightouchは接続元IPアドレスを公式ドキュメントで公開しており、RedshiftのSecurity GroupにそのIPレンジのみを許可することで不正アクセスを防ぎます。またHightouch専用の読み取り専用ユーザーを作成し、必要なスキーマのSELECT権限のみを付与することがセキュリティのベストプラクティスです。',
    source: 'Hightouch公式ドキュメント（セキュリティ設定）',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld05',
    text: 'AWS PrivateLinkを使ったHightouchとSnowflake/Redshiftの接続が必要になるのはどのような場合ですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchを無料プランで使う場合に必須',
      'Sync処理速度を2倍にしたい場合',
      'インターネット経由の通信を避け、AWSのプライベートネットワーク内だけで通信させたいセキュリティ要件がある場合',
      'Sync実行回数を増やしたい場合',
    ],
    correctIndex: 2,
    explanation: 'AWS PrivateLinkを使うと、Hightouchとデータソース（RedshiftやSnowflake on AWS）間の通信がインターネットを経由せず、AWSのプライベートネットワーク内で完結します。金融・医療・官公庁など高いセキュリティ要件を持つ企業で採用されます。Hightouchはこのようなプライベート接続に対応しています。',
    source: 'Hightouch公式ドキュメント（セキュリティ / PrivateLink）',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld06',
    text: 'Amazon S3をHightouchのSourceとして使う場合、S3上のファイルをどのように扱いますか？',
    type: 'multiple_choice',
    options: [
      'S3のファイルはJSONのみ対応。CSVやParquetは対応していない',
      'CSV・JSON・Parquetなどのファイルをテーブルとして読み込み、SQLでクエリできる',
      'S3はHightouchのSourceとしては使えない（DestinationのみS3が使える）',
      'S3のファイルは自動的にRedshiftにインポートされてからHightouchが使う',
    ],
    correctIndex: 1,
    explanation: 'HightouchはAmazon S3を直接Sourceとして接続でき、S3上のCSV・JSON・Parquet等のファイルをテーブルとして扱いSQLでクエリできます。また、S3をDestinationとして使い、Sync結果をファイルとして書き出すことも可能です。DWHを持たない場合のデータソースとしても活用できます。',
    source: 'Hightouch公式ドキュメント（S3 Source）',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld07',
    text: 'BigQueryの「オンデマンド課金」と「定額料金（Reservations）」の違いを踏まえ、Hightouchのような定期的なクエリを大量に実行するツールに適した選択はどれですか？',
    type: 'multiple_choice',
    options: [
      '常にオンデマンドが安い',
      '常に定額料金が安い',
      'クエリ量が少ない場合はオンデマンド、高頻度Syncで一定量以上のクエリを実行する場合は定額料金（Reservations）の方がコスト効率が高くなる可能性がある',
      'HightouchはBigQueryのコスト計算には影響しない',
    ],
    correctIndex: 2,
    explanation: 'BigQueryのオンデマンド課金はスキャンしたデータ量（TB単位）で課金されます。Hightouchのような定期的なSync（例：毎時間クエリ実行）では、クエリ回数・スキャン量が多くなるため、高頻度のSyncを運用する場合はBigQuery Reservations（定額スロット）の検討が必要です。Modelクエリの最適化（パーティション・クラスタリングの活用）も重要です。',
    source: 'Google Cloud公式ドキュメント + Hightouch最適化ガイド',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld08',
    text: 'GCPのサービスアカウントキー（JSON）をHightouchに設定する際のセキュリティ上の注意点として正しいものはどれですか？',
    type: 'multiple_choice',
    options: [
      'サービスアカウントにはBigQueryの全権限（BigQuery Admin）を付与すべき',
      'JSONキーは一度Hightouchに設定したら、定期的なローテーションは不要',
      'サービスアカウントには最小限の権限のみ付与し、JSONキーはGitなどに含めずHightouchのSecrets管理機能で安全に保管する',
      'サービスアカウントは複数プロジェクトで共有することが推奨される',
    ],
    correctIndex: 2,
    explanation: 'GCPサービスアカウントのJSONキーは認証情報（秘密鍵）です。BigQuery Data ViewerとBigQuery Job Userなど最小限の権限のみを付与し、定期的なキーローテーション（90日ごと等）を実施します。Gitリポジトリへの漏洩は特に危険です。HightouchのSecrets管理機能を活用することを推奨します。',
    source: 'GCP IAMベストプラクティス + Hightouch公式ドキュメント',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld09',
    text: 'DatabricksをHightouchのSourceとして使う場合、「Delta Lake」の特徴として正しいのはどれですか？',
    type: 'multiple_choice',
    options: [
      'Delta Lakeはリアルタイムデータのみをサポートするストリーミング専用ストレージ',
      'Delta Lakeは更新・削除（UPDATE/DELETE）をサポートし、ACIDトランザクションを提供するDatabricksのストレージレイヤー',
      'Delta LakeはDatabricks専用の形式でHightouchから直接読み取れない',
      'Delta LakeはS3やGCSには保存できずDatabricks内部のみで使用できる',
    ],
    correctIndex: 1,
    explanation: 'Delta LakeはApache Sparkベースのオープンソースストレージレイヤーで、ACIDトランザクション・UPDATE/DELETE操作・タイムトラベル（過去状態の参照）をサポートします。HightouchはDatabricksのDelta Lakeテーブルを直接Sourceとして扱え、最新のスナップショットに対してSQLクエリを実行できます。',
    source: 'Databricks公式ドキュメント + Hightouch Databricks Source',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld10',
    text: 'BigQueryに設定された「行レベルセキュリティ（Row-Level Security）」は、HightouchのサービスアカウントからのクエリにどのようにHightouchの動作に影響しますか？',
    type: 'multiple_choice',
    options: [
      'HightouchはRow-Level Securityを無視してすべてのデータにアクセスできる',
      'HightouchのサービスアカウントにRow-Level Securityのポリシーが適用され、アクセス可能な行のみがSyncに使われる',
      'Row-Level SecurityはHightouchと互換性がなく、エラーになる',
      'HightouchはRow-Level Securityをバイパスするために管理者権限が必要になる',
    ],
    correctIndex: 1,
    explanation: 'BigQueryのRow-Level Security（行レベルセキュリティ）はサービスアカウントにも適用されます。HightouchのサービスアカウントがアクセスできるFilter Policyに従って、読み取れる行が制限されます。意図しないデータへのアクセスを防ぐには、HightouchのサービスアカウントがアクセスすべきデータのみにFilterを設定します。',
    source: 'BigQuery公式ドキュメント（Row-Level Security）',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld11',
    text: 'HightouchはAWS EventBridgeなど外部システムからAPIでSyncをトリガーできますか？',
    type: 'true_false',
    options: ['○ できる（HightouchのREST API経由でSyncをトリガー可能）', '× できない（HightouchはスケジュールのみでAPIトリガーには非対応）'],
    correctIndex: 0,
    explanation: 'HightouchはREST APIを提供しており、外部システムからHTTP POSTリクエストを送ることで特定のSyncを起動できます。例えば「S3に新しいファイルが到着したらEventBridgeルールが起動し、HightouchのAPI経由でSyncを実行する」というパターンが実現できます。AirflowやdbtのDAG完了後にSyncを連鎖実行する場合にも活用されます。',
    source: 'Hightouch公式ドキュメント（API Trigger）',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld12',
    text: 'Amazon Redshift Spectrumを使うと、HightouchのModelでどのようなデータを扱えますか？',
    type: 'multiple_choice',
    options: [
      'Redshift SpectrumはHightouchとは無関係な機能',
      'S3に保存されたデータをRedshiftの外部テーブルとして定義し、HightouchのModelクエリでRedshift内部テーブルとS3データを統合して使える',
      'Redshift SpectrumはBigQueryとの接続専用機能',
      'HightouchのSync結果をRedshift Spectrumでバックアップする機能',
    ],
    correctIndex: 1,
    explanation: 'Redshift Spectrumを使うと、S3に保存されたデータをRedshiftの外部テーブルとして参照できます。HightouchのModelでは、Redshiftの内部テーブルとSpectrum外部テーブルをJOINしたクエリも実行可能です。これにより、DWH内データとS3データレイク上のデータを統合してマーケティングツールに送ることができます。',
    source: 'AWS公式ドキュメント（Redshift Spectrum）',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld13',
    text: 'HightouchがBigQueryに対してクエリを実行した場合、そのBigQueryのスキャン費用はどこに請求されますか？',
    type: 'multiple_choice',
    options: [
      'HightouchのGCPアカウントに課金されるため、ユーザー側への課金はない',
      'Hightouchのサービスアカウントが属するGCPプロジェクトに対してBigQueryのスキャン料金が課金される',
      'GoogleがHightouchパートナー料金として一括請求するため個別課金はない',
      'BigQueryのクエリはHightouchを通じて実行しても無料',
    ],
    correctIndex: 1,
    explanation: 'HightouchからBigQueryへのクエリ実行は、HightouchのサービスアカウントのGCPプロジェクトに課金されます（オンデマンド課金の場合）。頻繁にSyncを実行すると、そのプロジェクトのBigQueryコストが増加します。クエリの最適化（パーティション・クラスタリングの活用）でコストを抑えることが重要です。',
    source: 'BigQuery課金ドキュメント + Hightouch最適化',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld14',
    text: 'Google Cloud Storage（GCS）をHightouchのDestinationとして使う典型的なユースケースはどれですか？',
    type: 'multiple_choice',
    options: [
      'GCSはHightouchのDestinationとしては使えない',
      'HightouchのSync結果（CSV/JSON）をGCSバケットに書き出し、後続のシステムで活用する',
      'GCSにHightouchのログを自動バックアップする',
      'GCSをキャッシュとしてHightouchのSync速度を高速化する',
    ],
    correctIndex: 1,
    explanation: 'HightouchはGoogle Cloud Storage（GCS）をDestinationとして使用でき、Sync結果をCSVやJSONファイルとしてGCSバケットに書き出せます。これにより「DWHのデータをHightouchでフィルタリング・整形してGCSに出力し、その後BigQuery・Dataflow等の後続処理に渡す」というパイプラインが実現できます。',
    source: 'Hightouch公式ドキュメント（GCS Destination）',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld15',
    text: 'HightouchでSnowflake on AWSを使う場合、「Snowflakeのネットワークポリシー」とHightouchの接続はどう関係しますか？',
    type: 'multiple_choice',
    options: [
      'Snowflakeのネットワークポリシーはクラウドプロバイダーに依存しないため関係ない',
      'SnowflakeのネットワークポリシーでHightouchのIPアドレス範囲を許可リストに追加する必要がある',
      'HightouchはSnowflakeのネットワークポリシーを自動的にバイパスできる',
      'Snowflakeのネットワークポリシーはユーザー認証後には適用されない',
    ],
    correctIndex: 1,
    explanation: 'SnowflakeにはIPホワイトリストを設定するネットワークポリシー機能があります。HightouchからSnowflakeに接続するためには、HightouchのIPアドレス範囲（公式ドキュメントで公開）をSnowflakeのネットワークポリシーの許可リストに追加する必要があります。これを設定しないと接続が拒否されます。',
    source: 'Snowflake公式ドキュメント + Hightouch接続ガイド',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld16',
    text: 'BigQueryの「マテリアライズドビュー（Materialized View）」をHightouchのModelとして使うメリットはどれですか？',
    type: 'multiple_choice',
    options: [
      'マテリアライズドビューはHightouchのModelとして使用できない',
      'マテリアライズドビューを使うと、事前計算済みのキャッシュを参照するためSync実行時のスキャンコストと時間を削減できる',
      'HightouchはマテリアライズドビューをSyncするとビューが自動更新される',
      'マテリアライズドビューはHightouchのDestinationとして使う機能である',
    ],
    correctIndex: 1,
    explanation: 'BigQueryのマテリアライズドビューは事前計算・キャッシュされた結果を持つ仮想テーブルです。複雑な集計クエリを事前にマテリアライズドビューとして定義し、HightouchのModelからそのビューを参照することで、Sync実行時のクエリコストと時間を大幅に削減できます。',
    source: 'BigQuery公式ドキュメント（Materialized Views）',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld17',
    text: 'HightouchでAmazon Redshiftを使う際、「WLM（Workload Management）」を設定する理由として正しいのはどれですか？',
    type: 'multiple_choice',
    options: [
      'HightouchはWLMの専用キューがないと接続できない必須設定である',
      'HightouchのクエリをBI・分析クエリと同じキューで実行するとリソース競合が起きるため、Hightouch専用キューを設定してクエリリソースを分離する',
      'WLMを設定するとHightouchのSync速度が自動的に最速になる',
      'WLMはRedshiftのセキュリティ機能であり、Hightouchのアクセス制御に使う',
    ],
    correctIndex: 1,
    explanation: 'RedshiftのWLM（ワークロード管理）は、クエリグループ・ユーザーグループごとに専用キューを割り当てる機能です。HightouchのクエリをBIツールや分析クエリと同じキューで実行すると、リソース競合で互いのパフォーマンスが低下します。「Hightouch専用ユーザー」を作りそのユーザーのクエリを専用キューにルーティングすることで影響を分離できます。',
    source: 'AWS Redshift WLMドキュメント',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld18',
    text: 'GCPの「VPC Service Controls」をBigQueryに設定している企業がHightouchを導入する場合、どのような対応が必要ですか？',
    type: 'multiple_choice',
    options: [
      'VPC Service ControlsはHightouchとの接続を完全にブロックするため、BigQueryをHightouchのSourceにできない',
      'HightouchのサービスアカウントをVPC Service Controlsのアクセスポリシーに含め、BigQueryへのアクセスを許可するアクセスレベルを設定する',
      'Hightouch利用中はVPC Service Controlsを無効化する必要がある',
      'VPC Service ControlsはBigQueryには適用されない',
    ],
    correctIndex: 1,
    explanation: 'GCP VPC Service Controlsは、保護されたGCPサービス（BigQueryなど）へのアクセスをVPCネットワーク境界で制御します。Hightouchからのアクセスを許可するには、HightouchのサービスアカウントをService Control Policyの「アクセスレベル」に追加し、外部サービスからのアクセスを明示的に許可する設定が必要です。',
    source: 'GCP VPC Service Controls公式ドキュメント',
    difficulty: 3,
    category: 'cloud_infra',
  },
  {
    id: 'cld19',
    text: 'AWS GlueでETL処理をしたデータをHightouchで活用するには、どのような構成が一般的ですか？',
    type: 'multiple_choice',
    options: [
      'AWS Glueデータカタログを直接HightouchのSourceとして接続できる',
      'Glueで変換・整備されたデータをS3やRedshiftに書き込み、そのS3やRedshiftをHightouchのSourceとして接続する',
      'HightouchはAWS GlueとネイティブなAPIで直接統合されており、Glueジョブ完了後に自動でSyncが起動する',
      'AWS GlueはGCPのサービスであるためAWS上のHightouchとは連携できない',
    ],
    correctIndex: 1,
    explanation: 'AWS GlueはETLサービスで、データを変換してS3やRedshiftに格納します。HightouchはAWS Glueのデータカタログに直接接続する機能はありませんが、Glueで処理・整備されたデータの保存先（S3・Redshift）をSourceとして接続することで、Glueパイプラインの後段にHightouchを位置付けることができます。',
    source: 'AWS Glue + Hightouch活用ガイド',
    difficulty: 2,
    category: 'cloud_infra',
  },
  {
    id: 'cld20',
    text: 'BigQueryの「クラスタリング（Clustering）」をHightouchのModelクエリで活用するとどのようなメリットがありますか？',
    type: 'multiple_choice',
    options: [
      'クラスタリングを使うとHightouchのSync速度が自動的に2倍になる',
      'クラスタリング列でWHERE句やJOINをするとBigQueryがブロックをプルーニング（スキップ）し、スキャン量が減りコストと速度が改善される',
      'クラスタリングは書き込み専用の最適化でSELECTには効果がない',
      'クラスタリングを使うとBigQueryの料金が自動的に割引になる',
    ],
    correctIndex: 1,
    explanation: 'BigQueryのクラスタリングはテーブルデータをクラスタリング列の値でソートして格納します。HightouchのModelクエリでクラスタリング列にWHERE条件をつけると、BigQueryがブロックレベルでデータをプルーニング（不要なブロックをスキップ）し、スキャン量が削減されます。パーティションと組み合わせると更に効果的です（パーティションプルーニング→クラスタープルーニングの順）。',
    source: 'BigQuery公式ドキュメント（クラスタリング）',
    difficulty: 3,
    category: 'cloud_infra',
  },

  // ===== 上級Hightouch機能（30問） =====
  {
    id: 'adv01',
    text: 'Hightouchの「差分同期（Diff-based Sync）」とはどのような仕組みですか？',
    type: 'multiple_choice',
    options: [
      '変更されたデータのみを検出してDestinationに送信し、変更のないレコードは送信をスキップする仕組み',
      '毎回全件データをDestinationに送信して上書きする仕組み',
      'DWH内のデータを差分バックアップする機能',
      '2つのDestinationを比較して差分を出力する機能',
    ],
    correctIndex: 0,
    explanation: 'Hightouchの差分同期（Diff-based Sync）は、前回のSync以降に「追加・変更・削除」されたレコードのみを検出してDestinationに送信します。全件を毎回送るフルSync（Full Refresh）と異なり、変更分だけを送るため処理効率が高く、Destinationへの不要な更新も減ります。レコードの主キー（Primary Key）を基に変更を検出します。',
    source: 'Hightouch公式ドキュメント（Sync Mode）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv02',
    text: 'Hightouchの「モデル（Model）」と「オーディエンス（Audience）」の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      '「モデル」と「オーディエンス」は同じ意味で使われる',
      'モデルはSQLで定義したデータセット（テーブル）で、オーディエンスはCustomer Studio上でUIを使ってモデルからフィルタリングして作る特定ユーザーグループ',
      'モデルはDestinationの設定で、オーディエンスはSourceの設定',
      'モデルはBigQuery専用、オーディエンスはSnowflake専用の概念',
    ],
    correctIndex: 1,
    explanation: 'Hightouchでは「モデル（Model）」がSQLや視覚的なクエリビルダーで定義したデータセット（ユーザーテーブルなど）を指します。「オーディエンス（Audience）」はCustomer Studio上でそのモデルをベースに、ノーコードのUIを使って「年齢30歳以上かつ直近30日間購入あり」のようなフィルタリングで作る特定ユーザーグループです。',
    source: 'Hightouch公式ドキュメント（Model vs Audience）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv03',
    text: 'HightouchのMatch Booster機能はどのような目的で使いますか？',
    type: 'multiple_choice',
    options: [
      'DWHのクエリを高速化するためのキャッシュ機能',
      'Meta AdsやGoogle Adsなどにオーディエンスをアップロードする際、複数の識別子をハッシュ化して広告プラットフォーム側のユーザーマッチング精度を高める機能',
      'SyncのエラーレコードをAIが自動修正する機能',
      'Hightouchのライセンス数を最適化するための機能',
    ],
    correctIndex: 1,
    explanation: 'Match Boosterは、Meta AdsやGoogle Adsなどにカスタムオーディエンスをアップロードする際に、複数の識別子（メール・電話・氏名・住所など）を組み合わせてハッシュ化し、広告プラットフォーム側でのユーザーマッチング精度を高める機能です。マッチ率を向上させることで広告のリーチ精度が上がります。',
    source: 'Hightouch公式ドキュメント（Match Booster）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv04',
    text: 'HightouchのJourneys（ジャーニー）機能とはどのようなものですか？',
    type: 'multiple_choice',
    options: [
      '営業担当者のスケジュール管理ツール',
      'ユーザーの行動やイベントを起点に、条件分岐・タイマー・複数Destinationへの送信などを組み合わせたカスタマージャーニーをノーコードで構築できる機能',
      'DWHのデータを旅行会社向けにカスタマイズする機能',
      'HightouchのSyncログを視覚的に確認するダッシュボード機能',
    ],
    correctIndex: 1,
    explanation: 'HightouchのJourneysは、単発のSyncを超えた「ユーザー行動に連動した一連のコミュニケーション」を設計する機能です。「初回購入 → 3日後にサンクスメール → 7日後にクロスセルオファー → 未反応なら14日後にリマインダー」のような複雑なシナリオをHightouchのUI上で構築できます。',
    source: 'Hightouch公式ドキュメント（Journeys）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv05',
    text: 'HightouchのSplit機能を使ってA/Bテストを行う場合の正しい説明はどれですか？',
    type: 'multiple_choice',
    options: [
      'Split機能はWebページのUI要素をA/Bテストする機能',
      'AudienceをランダムにA群・B群（・コントロール群）に分割し、それぞれ異なるDestinationや施策に送り分けることでマーケティング施策のA/Bテストができる',
      'Split機能はDWH上のテーブルを分割して保存する機能',
      'SplitはHightouchのWorkspace（作業環境）を分割する機能',
    ],
    correctIndex: 1,
    explanation: 'HightouchのSplit機能を使うと、同一Audienceをランダムに複数のグループに分割し、グループAはMoEngageでメール配信、グループBはLine広告、グループCはコントロール（配信なし）、といった形で異なる施策に振り分けられます。施策の効果測定・比較に有効です。',
    source: 'Hightouch公式ドキュメント（Split）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv06',
    text: 'HightouchのSync実行モード「Full Sync」と「Incremental Sync」の違いはどれですか？',
    type: 'multiple_choice',
    options: [
      'Full Syncは全件をDestinationに送信する。Incremental Syncは前回Sync以降の変更（追加・更新・削除）分のみを送信する',
      'Full SyncはBigQuery専用、Incremental SyncはSnowflake専用',
      'Full Syncはリアルタイム処理、Incremental Syncはバッチ処理',
      'Full SyncとIncremental Syncは実行速度が違うだけで結果は同じ',
    ],
    correctIndex: 0,
    explanation: 'Full Sync（フルシンク）は毎回全レコードをDestinationに送信します。Incremental Sync（インクリメンタルシンク）は前回のSync以降に変更されたレコードのみを検出して送信します。処理効率はIncremental Syncの方が高いですが、Full Syncはシンプルで「全量の洗い替え」に適しています。Destinationの仕様やデータ量に応じて選択します。',
    source: 'Hightouch公式ドキュメント（Sync Modes）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv07',
    text: 'HightouchのAPI Trigger機能で、外部システムからSyncを起動する場合に使うものはどれですか？',
    type: 'multiple_choice',
    options: [
      'HightouchのSlackアプリからコマンドを送信する',
      'HightouchのREST APIに対してHTTP POSTリクエストを送り、特定のSyncを手動起動する',
      'AWS CloudWatchのアラームを設定してHightouchに通知する',
      'HightouchはAPIからのSyncトリガーには対応していない',
    ],
    correctIndex: 1,
    explanation: 'HightouchはREST APIを提供しており、外部システムからHTTP POSTリクエストを送ることで特定のSyncを起動できます。AirflowやdbtのDAG完了後、CI/CDパイプラインのデプロイ後など「特定のイベント後にSyncを実行したい」ケースで活用されます。APIキー認証でセキュアに呼び出せます。',
    source: 'Hightouch公式ドキュメント（API Trigger）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv08',
    text: 'Hightouchの「Traits（トレイツ）」機能はどのようなものですか？',
    type: 'multiple_choice',
    options: [
      'ユーザーの性格特性を自動分析するAI機能',
      'DWHのデータから「最終購入日」「過去30日の購入金額合計」などのユーザー属性（計算値）を定義して、Audienceのフィルタや配信データとして使える機能',
      'HightouchのUIのデザインテーマを変更する機能',
      'SyncのエラーをTrack（追跡）する機能',
    ],
    correctIndex: 1,
    explanation: 'Hightouchのtraits（トレイツ）は、DWHの複数テーブルから計算・集計した値をユーザー属性として定義する機能です。例えば「最終購入日」「30日間の購入金額」「購入回数」などを事前に計算しtraitsとして保存しておけば、Customer StudioでSQLを書かずにこれらの条件を組み合わせてAudienceを構築できます。',
    source: 'Hightouch公式ドキュメント（Traits）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv09',
    text: 'Hightouchで「dbt（Data Build Tool）のモデル」をSourceとして活用するには、どのような連携構成になりますか？',
    type: 'multiple_choice',
    options: [
      'dbtモデルを直接HightouchのModelとして使用できる専用の連携機能がある',
      'dbtが生成したテーブル・ビューはDWH（BigQuery/Snowflakeなど）に書き込まれるため、HightouchはそのDWHを通じてdbtモデルの成果物にアクセスする',
      'Hightouchはdbtとは連携できない',
      'dbtモデルはHightouchのDestinationとして使う機能',
    ],
    correctIndex: 1,
    explanation: 'dbtはDWH上でSQLモデルを定義・実行し、結果をDWH内のテーブルやビューとして書き込むツールです。「dbt run → DWH上にテーブル生成 → HightouchがそのテーブルをModelとして参照 → Sync実行」という流れになります。HightouchはdbtCloudとのネイティブ連携（dbt完了後のSyncトリガーなど）も提供しています。',
    source: 'Hightouch公式ドキュメント（dbt integration）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv10',
    text: 'HightouchのWorkspace（ワークスペース）を複数運用する代表的な理由はどれですか？',
    type: 'multiple_choice',
    options: [
      '複数Workspaceを作ると料金が安くなるため',
      '開発・ステージング・本番環境を分離したり、事業部・ブランド・地域ごとにデータと権限を分けるため',
      'HightouchはWorkspaceを1つしか作れないため、複数のWorkspaceは作れない',
      '複数WorkspaceはBigQueryとの接続にのみ必要な設定',
    ],
    correctIndex: 1,
    explanation: 'Hightouchでは複数のWorkspaceを作成し、それぞれ独立したSource・Destination・Sync・ユーザー権限を管理できます。代表的な用途は「開発/本番環境の分離」「事業部ごとの独立した管理」「ブランドや地域ごとのデータ分離」です。SSO（シングルサインオン）との組み合わせで大規模な組織管理も可能です。',
    source: 'Hightouch公式ドキュメント（Workspace管理）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv11',
    text: 'HightouchのGit Sync（バージョン管理連携）機能を使うメリットはどれですか？',
    type: 'multiple_choice',
    options: [
      'GitのリポジトリをHightouchのDestinationとして使える',
      'HightouchのSync設定（Model・Audienceの定義など）をGitリポジトリで管理でき、変更履歴の追跡・コードレビュー・CIパイプラインとの統合が可能になる',
      'GitHubのコードをHightouchが自動的にDWHにインポートする',
      'Git Syncを使うとHightouchのUIが不要になる',
    ],
    correctIndex: 1,
    explanation: 'HightouchのGit Sync機能では、ModelのSQLやSync設定をYAML/JSONとしてGitリポジトリと同期できます。これにより、変更のPull Request・コードレビュー・CI/CDパイプラインとの統合が可能になり、エンジニアリングのベストプラクティスをHightouchの設定管理に適用できます。',
    source: 'Hightouch公式ドキュメント（Git Sync）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv12',
    text: 'HightouchはTerraformプロバイダーを提供していますか？',
    type: 'true_false',
    options: ['○ 提供している（HightouchリソースをTerraformでIaC管理できる）', '× 提供していない'],
    correctIndex: 0,
    explanation: 'HightouchはTerraformプロバイダーを公式に提供しており、Source・Destination・Sync・Workspaceなどの設定をTerraformのHCLコードとして管理できます。これにより、インフラと同様にHightouchの設定もコードで管理・バージョン管理でき、環境の再現性が高まります。',
    source: 'Hightouch公式ドキュメント（Terraform）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv13',
    text: 'HightouchのAlertingでSyncの失敗などを通知できる先として正しいのはどれですか？',
    type: 'multiple_choice',
    options: [
      'Eメールのみ対応',
      'PagerDutyのみ対応',
      'Slack・メール・PagerDuty・OpsGenieなど複数の通知先を設定できる',
      'Hightouchにはアラート機能がない',
    ],
    correctIndex: 2,
    explanation: 'HightouchのAlertingでは、Syncの失敗・エラー閾値超過・スケジュール遅延などのイベントに対して、Slack・メール・PagerDuty・OpsGenieなど複数の通知チャネルに通知を送れます。これにより、Sync障害を早期に検知し迅速に対処できます。',
    source: 'Hightouch公式ドキュメント（Alerting）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv14',
    text: 'HightouchのCustomer Studio（Audience Hub）でビジネスユーザーがSQLなしにオーディエンスを作れる仕組みはどれですか？',
    type: 'multiple_choice',
    options: [
      'AIがユーザーの思考を読み取って自動的にSQLを生成する',
      'エンジニアが事前にモデル・Traitsを設定しておき、ビジネスユーザーはドラッグ＆ドロップやプルダウン選択でフィルター条件を組み合わせてオーディエンスを定義する',
      'ビジネスユーザーがCSVをアップロードしてオーディエンスを作る',
      'ビジネスユーザーがチャットボットで条件を入力するとSQLが自動生成される',
    ],
    correctIndex: 1,
    explanation: 'Customer Studio（Audience Hub）では、エンジニアがModelとTraitsを事前にセットアップします。その後、ビジネスユーザー（マーケターなど）がUIから「年齢が30-50歳」「最終購入から60日以内」「購入カテゴリ = 食品」のような条件を選択・組み合わせることで、SQLを書かずにオーディエンスを自分で定義できます。',
    source: 'Hightouch公式ドキュメント（Customer Studio）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv15',
    text: 'HightouchのEvent Triggered Sync（イベントトリガー同期）はどのような仕組みですか？',
    type: 'multiple_choice',
    options: [
      '毎時・毎日のスケジュールが「イベントトリガー」と呼ばれている',
      'ユーザーの行動イベント（購入・カート追加など）をストリーミングソースから受け取り、そのイベントを起点にリアルタイムでSyncを実行する仕組み',
      'ITシステムの障害イベントを検知してSyncを一時停止する仕組み',
      'Hightouchにイベントトリガー機能は存在しない',
    ],
    correctIndex: 1,
    explanation: 'Event Triggered Syncは、ユーザーが特定のアクション（購入・フォーム送信・カート放棄など）を起こした瞬間のイベントをKafka・Segment・Kinesisなどのストリーミングソースから受け取り、そのイベントを即座にSyncのトリガーとして使う仕組みです。バッチ型の定期Syncと比較して、イベント発生から連携先ツールへの反映までの遅延を大幅に短縮できます。',
    source: 'Hightouch公式ドキュメント（Event Triggered Syncs）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv16',
    text: 'HightouchでSalesforceをDestinationとして使う場合、「SalesforceのAPIコール制限（API Limit）」で注意すべきことはどれですか？',
    type: 'multiple_choice',
    options: [
      'HightouchはSalesforceのAPIコール制限を無制限に回避できる',
      'HightouchはSalesforceのREST/Bulk APIを使ってデータを同期するため、SalesforceのデイリーAPIコール制限の消費量を考慮してSync頻度・レコード数を設計する必要がある',
      'HightouchはSalesforceに対してAPIを使わずデータベース直接接続で同期する',
      'SalesforceのAPIコール制限はEnterprise版では存在しない',
    ],
    correctIndex: 1,
    explanation: 'HightouchはSalesforceのREST API・Bulk APIを使ってデータを同期します。SalesforceにはデイリーAPIコール上限（契約プランによって異なる）があるため、大量レコードの高頻度Syncを設計する場合はAPIコール消費量を見積もる必要があります。HightouchはBulk APIを優先して使いコール数を最小化するよう設計されています。',
    source: 'Salesforce API制限 + Hightouch Salesforce Destination',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv17',
    text: 'HightouchのAudience Overlap（オーバーラップ分析）機能とは何ですか？',
    type: 'multiple_choice',
    options: [
      'AWSとGCPのコスト比較分析機能',
      '複数のAudience間でユーザーが重複している割合を視覚的に確認できる機能で、重複配信を防ぐのに活用する',
      'Sync処理が重複して実行されていないかチェックする機能',
      'Destinationツールのユーザーデータの重複を削除する機能',
    ],
    correctIndex: 1,
    explanation: 'Audience Overlap分析では、複数のAudience間でユーザーがどの程度重複しているかを視覚化できます。同じユーザーが複数の施策でターゲティングされていないかを確認し、重複配信によるユーザー体験の悪化やコスト無駄を防ぐのに役立ちます。Priority List機能と組み合わせることで重複ユーザーの振り分けも制御できます。',
    source: 'Hightouch公式ドキュメント（Audience Overlap）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv18',
    text: 'HightouchのDecisioning（ディシジョニング）機能とはどのようなものですか？',
    type: 'multiple_choice',
    options: [
      'Hightouchの経営判断を支援するBIダッシュボード機能',
      'AIと機械学習を使って、個々のユーザーに対して最適なオファー・メッセージ・チャネルをリアルタイムに決定する次世代パーソナライゼーション機能',
      'Syncを実行するかどうかを手動で承認する承認フロー機能',
      'A/Bテストの結果を自動的に採用・不採用に決定する機能',
    ],
    correctIndex: 1,
    explanation: 'HightouchのDecisioningは、「次のベストアクション（Next Best Action）」を個人単位でリアルタイムに決定する機能です。DWHのデータ・行動履歴・プロペンシティスコアを組み合わせ、各ユーザーに送るべきオファー・チャネル・タイミングをAI/MLで最適化します。従来のセグメント単位施策を超えた1対1パーソナライゼーションを実現します。',
    source: 'Hightouch公式ドキュメント（Decisioning）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv19',
    text: 'HightouchのSyncで「Upsert（アップサート）」モードとはどのようなものですか？',
    type: 'multiple_choice',
    options: [
      'Destinationの全レコードを削除して新規に全件挿入するモード',
      'プライマリキーで照合し、Destinationに存在するレコードは更新（Update）、存在しないレコードは新規追加（Insert）するモード',
      'Destinationへの書き込みを上向き（上書き）に最適化するモード',
      'エラーが発生したレコードのみを再送するリトライモード',
    ],
    correctIndex: 1,
    explanation: 'Upsertモードは「更新（Update）＋挿入（Insert）」を組み合わせた動作で、プライマリキーで照合してDestinationにレコードが存在すれば更新、存在しなければ新規挿入します。既存のDestinationデータを保持しながら、新規・変更レコードだけを効率的に同期するため、多くのユースケースで推奨されるモードです。',
    source: 'Hightouch公式ドキュメント（Sync Modes）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv20',
    text: 'Hightouchの「Identity Resolution（IDリゾリューション）」機能が必要になるのはどのような場面ですか？',
    type: 'multiple_choice',
    options: [
      'ユーザーが本人確認（KYC）を行うための機能',
      '同一人物がログインID・匿名ID・メールアドレスなど複数の識別子を持つ場合に、それらを統合して一意のプロファイルとして管理する場面',
      'HightouchのユーザーアカウントのIDを管理する機能',
      'Google AdsのMatch IDを最適化する機能',
    ],
    correctIndex: 1,
    explanation: 'Identity Resolutionは、同一人物が異なるデバイス・チャネルで異なるIDで識別される場合（匿名Cookie・ログインID・メールアドレス・電話番号など）に、これらを統合して一意のプロファイルにまとめる処理です。HightouchではID解決されたデータをDWH上で管理し、一貫したユーザービューをAudienceやSyncに活用できます。',
    source: 'Hightouch公式ドキュメント（Identity Resolution）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv21',
    text: 'HightouchのModelでSQLを書く際、DWH上の全テーブル・全カラムにアクセスできますか？',
    type: 'multiple_choice',
    options: [
      '全テーブル・全カラムに自由にアクセスできる',
      'Hightouchに設定したDWHユーザー（サービスアカウント）が権限を持つテーブル・カラムのみアクセスできる',
      'Hightouchが自動的にアクセス権限を拡張する',
      'アクセスできるテーブルはHightouch社が事前に承認したもののみ',
    ],
    correctIndex: 1,
    explanation: 'HightouchのModelでアクセスできるデータは、DWH接続に使用したユーザー（またはサービスアカウント）の権限に完全に依存します。そのHightouchユーザーが持つテーブル・カラムのSELECT権限の範囲内でのみSQLを実行できます。これにより、Hightouch専用ユーザーに必要最小限の権限のみを付与することでデータアクセスを制御できます。',
    source: 'Hightouch公式ドキュメント（セキュリティ / 権限管理）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv22',
    text: 'HightouchでSnowflakeの「Dynamic Data Masking（動的データマスキング）」を使った場合、Hightouchのデータ取得はどうなりますか？',
    type: 'multiple_choice',
    options: [
      'HightouchはSnowflakeのマスキングポリシーを無視してマスク前のデータを取得できる',
      'HightouchのSnowflakeユーザーに適用されているマスキングポリシーに従い、マスク済みのデータがHightouchに返される',
      'HightouchはSnowflakeのマスキング機能に対応していない',
      'マスキングポリシーはSnowflakeへの書き込み時のみ適用される',
    ],
    correctIndex: 1,
    explanation: 'SnowflakeのDynamic Data Maskingは、SELECTクエリの実行時にユーザーのロールに応じてカラム値をマスクする機能です。HightouchのSnowflakeユーザーにマスキングポリシーが適用されていれば、Hightouchはマスク済みの値を取得します。機密カラム（PII等）を特定のロールにはマスクして見せる設計が可能です。',
    source: 'Snowflake Dynamic Data Masking + Hightouch接続ガイド',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv23',
    text: 'Hightouch AIのCopilot機能はどのような場面で活用されますか？',
    type: 'multiple_choice',
    options: [
      'DWHのデータを分析してレポートを自動生成する',
      '自然言語（日本語や英語）でオーディエンスの条件を入力すると、AIがSQLやAudienceのフィルター条件を生成してくれる機能',
      'Sync実行エラーを自動修正するAI',
      'Hightouchの料金プランをAIが最適化する',
    ],
    correctIndex: 1,
    explanation: 'Hightouch CopilotはAI（LLM）を活用して、「30日以上購入していない高LTVユーザーを抽出して」のような自然言語の指示からSQLやAudienceのフィルター条件を自動生成する機能です。ビジネスユーザーがさらに直感的にセグメントを作れるようになります。',
    source: 'Hightouch公式発表（AI Copilot）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv24',
    text: 'HightouchのHTTP Request Destinationで接続先APIの認証方式として対応しているのはどれですか？',
    type: 'multiple_choice',
    options: [
      'APIキー認証のみ対応',
      'Basic認証のみ対応',
      'APIキー・Bearer Token・Basic認証・OAuth2など複数の認証方式に対応している',
      '認証なし（パブリックAPI）のみ対応',
    ],
    correctIndex: 2,
    explanation: 'HightouchのHTTP Request Destinationは、REST APIを持つ任意のサービスとの連携に使います。認証方式としてAPIキー（ヘッダー・クエリパラメータ）・Bearer Token・Basic認証・OAuth2など複数の方式に対応しているため、様々なAPIの認証要件に対応できます。',
    source: 'Hightouch公式ドキュメント（HTTP Request Destination）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv25',
    text: 'Hightouchの「行レベルエラーハンドリング（Row-level error handling）」が重要な理由はどれですか？',
    type: 'multiple_choice',
    options: [
      '1件のエラーがあってもSync全体が止まらず、エラーレコードをスキップして他のレコードの処理を続けられるため、運用の安定性が高まる',
      '行レベルエラーハンドリングはHightouchの有料オプション機能',
      'エラーが発生したレコードは自動的に修正される',
      '行レベルエラーハンドリングにより、Syncが2倍の速度で実行される',
    ],
    correctIndex: 0,
    explanation: 'HightouchはSync実行時に個々のレコードのエラーを行レベルで管理します。エラーが一部のレコードで発生しても、他のレコードの処理は継続されます（エラー閾値の設定もできます）。エラーになったレコードと理由はUIで詳細確認でき、部分的な失敗がSyncをブロックしない設計になっています。',
    source: 'Hightouch公式ドキュメント（Error Handling）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv26',
    text: 'HightouchのSync Sequenceを使ってできることはどれですか？',
    type: 'multiple_choice',
    options: [
      '複数のSyncを順番に（直列に）実行し、先行Syncが成功したら次のSyncを起動する依存関係を定義できる',
      '複数のSyncを同時（並列）に実行するための最適化機能',
      'Syncの実行回数をシーケンシャルに番号付けして管理する機能',
      'HightouchにSync Sequenceという機能は存在しない',
    ],
    correctIndex: 0,
    explanation: 'Sync Sequence機能を使うと、「Sync Aが成功したら→Sync Bを実行、Sync Bが成功したら→Sync Cを実行」のような直列の依存関係を定義できます。データパイプラインの順序制御（例：「ユーザーデータの更新→セグメント計算→広告への送信」）に活用できます。',
    source: 'Hightouch公式ドキュメント（Sync Sequence）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv27',
    text: 'HightouchのSSOに対応しているIdPとして正しいのはどれですか？',
    type: 'multiple_choice',
    options: [
      'Google Workspace SSOのみ対応',
      'Okta・Azure AD・Google WorkspaceなどSAML 2.0/OIDC準拠の主要なIdPに対応している',
      'SSOはEnterprise以上のプランでないと使えず、かつOkta専用',
      'HightouchはSSOには未対応',
    ],
    correctIndex: 1,
    explanation: 'HightouchのSSO（シングルサインオン）はSAML 2.0規格に対応しており、Okta・Azure AD（Microsoft Entra ID）・Google Workspace・OneLogin等の主要なIdP（Identity Provider）と連携できます。大企業での導入時にセキュリティポリシーに合わせたID管理が可能です。',
    source: 'Hightouch公式ドキュメント（SSO）',
    difficulty: 2,
    category: 'advanced',
  },
  {
    id: 'adv28',
    text: 'HightouchでMeta（Facebook）のCustom Audienceに広告オーディエンスをSyncする際、個人情報（PII）はどのように扱われますか？',
    type: 'multiple_choice',
    options: [
      '個人情報はHightouchのサーバーに保存されてからMetaに送信される',
      'HightouchはDWHから取得したPII（メール・電話・氏名など）をSHA-256でハッシュ化した上でMetaのAPIに送信し、HightouchのサーバーにPIIは保存されない',
      'MetaのAPI上では個人情報は暗号化されないため非推奨のSyncである',
      'Hightouchは個人情報をMeta APIに直接（平文で）送信する',
    ],
    correctIndex: 1,
    explanation: 'Meta（Facebook）のCustom Audienceに送信する際、Hightouchはメールアドレス・電話番号・氏名などのPIIをSHA-256ハッシュ化してからMetaのAPIに渡します。平文のPIIはHightouchのサーバーを通過せず、DWHから直接ハッシュ化されてMetaに送られます。これはMetaのカスタムオーディエンス利用規約にも準拠した安全な方式です。',
    source: 'Hightouch公式ドキュメント（Meta Ads Destination）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv29',
    text: 'HightouchのAudienceで「親子（Parent/Child）Audience」の構造を使うメリットはどれですか？',
    type: 'multiple_choice',
    options: [
      '親Audienceを定義しておくと、子AudienceはそのサブセットとなるフィルターをUIで追加するだけで作成でき、ベースとなる母集団を一元管理できる',
      '親AudienceはBigQuery専用で、子AudienceはSnowflake専用の機能',
      '親子Audienceにすると全てのSyncが2倍速で実行される',
      'Hightouchに親子Audienceという概念はない',
    ],
    correctIndex: 0,
    explanation: '親子Audienceの構造では、親Audienceで「有効ユーザー全体」などの大きな母集団を定義し、子Audienceでその母集団に追加フィルターをかけることで様々なサブセグメントを作ります。親Audienceのクエリを変更するだけで、全ての子Audienceに変更が反映されるため、ベース条件の一元管理が可能です。',
    source: 'Hightouch公式ドキュメント（Audience Hierarchy）',
    difficulty: 3,
    category: 'advanced',
  },
  {
    id: 'adv30',
    text: 'Hightouchの「Reverse ETLを使ったオペレーショナルアナリティクス」とはどのような考え方ですか？',
    type: 'multiple_choice',
    options: [
      'DWHのデータを分析してグラフ・レポートを作成すること',
      'DWHで分析・計算された洞察（スコア・セグメント・予測値など）を、営業・カスタマーサポート・マーケターが日常的に使うオペレーショナルツール（CRM・MAなど）に自動反映すること',
      'データアナリストがDWHの運用を行うこと',
      'HightouchがBI（ビジネスインテリジェンス）ツールを置き換えること',
    ],
    correctIndex: 1,
    explanation: 'オペレーショナルアナリティクスとは「分析の結果を分析ツール内で終わらせず、実際の業務ツールに組み込んで使う」考え方です。例えばDWHで計算した「チャーンリスクスコア」をSalesforceに自動同期してCSが確認できるようにしたり、「LTVスコア」をMA（MoEngage）に送ってパーソナライズ配信に使うことがこれにあたります。Hightouchはこの橋渡し役を担います。',
    source: 'Hightouch公式ブログ（Operational Analytics）',
    difficulty: 3,
    category: 'advanced',
  },
];

export const CATEGORIES = {
  basics: '基礎知識',
  reverse_etl_usecase: 'リバースETL・ユースケース',
  customer_studio: 'Customer Studio',
  workspace_mgmt: 'Workspace管理',
  integrations: '連携・インテグレーション',
  competitors: '競合比較',
  security: 'セキュリティ',
  cloud_infra: 'AWS・GCP基礎',
  advanced: '上級・応用機能',
};
